### ISSUE TITLE
Controller Files Have Incorrect Names

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#1]
This report is to officially file a bug reported to Mike Syson via email on 9/25/17.

-----------------
Environment
-----------------

(1) Branch: master
(2) Commit ID: 99693fab4a5ac2c68305b3f257b4e2a4430cc0ee
(3) How to recreate:
      (a) Access home url - https://store.usbong.ph/
      (b) The default controller is set to B.php
      (c) The url will return a 404 (route not found) error
(4) Note: This happens to majority of the pages.

-----------------
Analysis
-----------------

(1) The controller files named under the directory below are faulty:
      UsbongStore/usbong_store/application/controllers

(2) The files start with lower case letters.

(3) They should start with capital letters.
      (a) b.php should be B.php
      (b) account.php should be Account.php
      (c) and so on
     
-----------------
Resolution
-----------------

Mike Syson has resolved this in:

(1) Commit: 42038bbd42ce5ffe4e2d9786e597fbe155af2433
(2) Branch: master
(3) Date: 9/26/17

I have verified the fix.

**Comment by zent-lim** [comment]
I have verified Mike Syson's resolution in:

(1) Commit: 42038bbd42ce5ffe4e2d9786e597fbe155af2433
(2) Branch: master
(3) Date: 9/26/17

**Comment by masarapmabuhay** [comment]
Thank you, Zent!
