### ISSUE TITLE
Updated usbong_store/assets/images/banner_icons/dahon.png not used.

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#10]
Hi Zent,
I was able to update the layout design of:

`...application/views/auto-email/email_frame_simple_template.php
`

such that only 5 app icon images are used, instead of 10.

I also updated `dahon.png`, so that it now has a higher resolution: 148x148px.

Unfortunately, when I use auto-email to send a promotional email, the image used is still the pixelated version.

I have cleared my browser's cache history, yet the result is the same.

Would you know how I may be able to resolve this issue?

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
I was able to resolve the issue.

As it turned out, I only updated `dahon.png` in my `local` environment.

After updating the one in `prod`, and clearing my browser's cache, auto-email successfully sent a clearer version of `dahon.png`.

Thank you.

This case is now closed.

Peace,
Mike

**Comment by zent-lim** [comment]
Cool! 😁
