### ISSUE TITLE
Question: Do you use any convenient SQL commands?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#101]
Hi Zent,
I hope you are doing well.

May I kindly ask if you use
any convenient SQL commands
as you work on the Usbong Store
components, e.g. auto-email?

If yes, please do share them 
on our [Usbong Store Miscellaneous 
SQL Commands .txt file](https://github.com/usbong/UsbongStore/blob/master/db/Miscellaneous%20SQL%20Commands/Miscellaneous%20SQL%20Commands.txt).

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

None at the moment. :)

Have a  good evening ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! This case is now closed.

Thank you.

Peace,
Mike
