### ISSUE TITLE
Mobile Responsiveness: when in full screen, there are unaligned product items

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#103]
Hi Zent,
I hope you are doing well.

I have already updated my local version 
of the Usbong Store server
with your [newest code commit](https://github.com/usbong/UsbongStore/pull/102).

**Observation:**
1) When in full screen, there are unaligned product items, e.g. there are rows that have only 1 product item, even though there should be 6.

--> Am I correct in my understanding that this is because the updated View files, e.g. textbooks_v2, food_v2, will still be in the next Phase of the Usbong Store Mobile Responsiveness project upgrade?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike,

The problem should not be there.

NOTES:

(1) Here is how textbook catalog should look like on full screen:

      Url: https://store.usbong.ph/index.php/b/textbooks/

      Image:

![textbook](https://user-images.githubusercontent.com/8021327/43237225-8e21afe2-90bb-11e8-91fc-947502ca0415.png)

      Note: broken images are images that are not in my local environment.

(2) Here is how food catalog should look like on full screen:

     Url: https://store.usbong.ph/index.php/b/food/

     Image:

![food](https://user-images.githubusercontent.com/8021327/43237263-ae175432-90bb-11e8-8604-3759e309d24a.png)

Question:

(1) Was the mobile responsive switch activated on your local core controller?

(2) If yes, please send me screen shot of what you are seeing.

Morning!

**Comment by zent-lim** [comment]
Hi Mike,

I was able to recreate the problem in chrome.

![chrome](https://user-images.githubusercontent.com/8021327/43238006-e159e5fa-90be-11e8-9cd6-58eeaf425cff.png)

Analyzing it now.

**Comment by zent-lim** [comment]
Hi Mike,

I resolved the problem in zent repo fc0546356334ca7ac603740ce2fdc426a5b811e1.

The pull request is in:
https://github.com/usbong/UsbongStore/pull/104

REQUEST:

(1) Please check if this solves the problem in your environment.

(2) The file updated was a js file. Please clear your browser cache for the new js file to load.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

I have merged your pull request (https://github.com/usbong/UsbongStore/pull/104) with the Usbong Store master.

I have also cleared the browser cache of both my Google Chrome and Mozilla Firefox.

Unfortunately, your update did not resolve the issue.

**My ANSWERS to your QUESTIONS:**

(1) Yes, I have set the mobile responsive switch to TRUE in my local core controller.

(2) These are screenshots of what I see after merging your newest commit with my local version of the Usbong Store code.

a) Google Chrome

![image](https://user-images.githubusercontent.com/344066/43243882-397a6414-90db-11e8-9bc5-7462e9c79638.png)

b) Mozilla Firefox

![image](https://user-images.githubusercontent.com/344066/43243727-9634ecca-90da-11e8-9862-fa2da869f6f0.png)

Please never hesitate
to tell me if there's anything
else that you need.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Thank you for sending me an image.

I'd like to verify your environment's common.js file.

Using chrome, could you do the ff please?

![commonjs](https://user-images.githubusercontent.com/8021327/43244572-e0fedb64-90dd-11e8-9e55-21f6f04cf9fa.png)


(1) right click on page

(2) choose inspect element (new window appears)

(3) on new window, choose network (list of files appear)

(4) in list of files look for common.js and check line 11

(5) please check if the content of the line reads the ff:

`maxHeight = Math.ceil($(this).height());`

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

When I select `common.js` and then "Preview", it is blank.

In "Headers", this is what is shown:

a) General:

> Request URL: https://store.usbong.ph/assets/js/b/common.js
> Request Method: GET
> Status Code: 404 Not Found
> Remote Address: 52.33.56.147:443
> Referrer Policy: no-referrer-when-downgrade
> 

b) Request Headers:

> Provisional headers are shown
> Referer: http://localhost:8080/b/food/
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
> 

In my `application/config/config.php`, I use the following:
`$config['base_url'] = 'http://localhost:8080/';`

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Thanks for informing of the 404 error.

File: application/views/b/generic_mobile_responsive_catalog.php

Orig Code:

<script src="https://store.usbong.ph/assets/js/responsive_bootstrap_toolkit/bootstrap-toolkit.min.js"></script>

<script src="https://store.usbong.ph/assets/js/b/common.js"></script>

I will update to the ff so it can also run in local environment:

<script src="/assets/js/responsive_bootstrap_toolkit/bootstrap-toolkit.min.js"></script>
<script src="/assets/js/b/common.js"></script>

Please wait a while.

**Comment by zent-lim** [comment]
Hi Mike,

Kindly check if this resolves the problem:

(1) Code: zent repo 59035d2f80ac7b0578d9415651554f54aa6da362

(2) Pull Request: https://github.com/usbong/UsbongStore/pull/105

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

I have already merged your pull request
with Usbong Store master.

It seems to have resolved the issue,
except when I do the following steps:

1) Select the FOOD category.
2) Minimize the browser window that is in full screen.
3) Make the browser window full screen again.

**Result:**
1) There is a blank row after each row with product items.
2) If I visit another category, e.g. TOYS & COLLECTIBLES, the unaligned product item issue persists.

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

I have already merged your newest commit (https://github.com/usbong/UsbongStore/pull/106) with Usbong Store master.

(1) Yes, your newest commit resolved the issue.

(2) Your newest commit also resolved this issue.

This case is now closed.

Thank you.

Peace,
Mike
