### ISSUE TITLE
Mobile Responsiveness: No brackets in "Free Delivery"

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#108]
Hi Zent,
I hope you are doing well.

I noticed that "Free Delivery" does not have any brackets.
It should be "[Free Delivery]".

Having said this, I've put this issue as severity-low.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike,

Removal of bracket was done intentionally. It subjectively looked better
from my perspective.

I ll put the brackets back on monday then.

Happy weekend! 😊

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply!

OK! Yes, please put the brackets back.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I resolved this in:

(1) zent repo 76bb9728f9897ecd6c20af2098a4741b65d9e685

(2) pull request: https://github.com/usbong/UsbongStore/pull/112

![children](https://user-images.githubusercontent.com/8021327/43381112-2ca03a42-9406-11e8-8b46-638913cd1c16.png)

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, I can confirm that you've 
indeed resolved this issue.

This case is now closed.

Thank you.

Peace,
Mike
