### ISSUE TITLE
Mobile Responsiveness: "ESSENTIAL READING" not properly aligned

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#109]
Hi Zent,
I hope you are doing well.

In the Merchant page and the product type/category page, e.g. Books, Children's Books, Textbooks, "ESSENTIAL READING" is not properly aligned with the product item image.

This occurs both in Google Chrome and Mozilla Firefox.

1) Google Chrome

![image](https://user-images.githubusercontent.com/344066/43362033-018d6e18-9313-11e8-8179-029882298fcd.png)

2) Mozilla Firefox

![image](https://user-images.githubusercontent.com/344066/43362032-dea8b42a-9312-11e8-8308-89eec4602e1d.png)

What could be the probable cause?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike,

I was able to recreate the problem.

I ll contonue investigation on monday.

Happy weekend!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply!

OK!

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike,

(1) I resolved this in:

      (a) zent repo b430594385fc1eab71b7aa723a64a307e400a6f9

      (b) pull req: https://github.com/usbong/UsbongStore/pull/113

(2) Below is preview:

     (a) lg

![lg](https://user-images.githubusercontent.com/8021327/43434124-f8d9e210-94ac-11e8-8bae-2daf15392031.png)

     (b) md

![md](https://user-images.githubusercontent.com/8021327/43434130-fea62c76-94ac-11e8-8c15-0bdb499735f7.png)

     (c) sm

![sm](https://user-images.githubusercontent.com/8021327/43434134-043f8394-94ad-11e8-9c5f-36acbd991ed3.png)

     (d) xs

![xs](https://user-images.githubusercontent.com/8021327/43434140-09034f50-94ad-11e8-902b-e611939ddfec.png)

Morning!

P.S.
No unresolved tickets left. Standing by for feedback.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, I can confirm that you've resolved this issue.

This case is now closed.

Thank you.

Peace,
Mike
p.s. OK!
