### ISSUE TITLE
Mobile Responsiveness: In Merchant page, Merchant category "TOYS & COLLECTIBLES" now occupies 2 rows

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#110]
Hi Zent,
I hope you are doing well.

In the Merchant page, Merchant category "TOYS & COLLECTIBLES" now occupies 2 rows.

This occurs both in Google Chrome and Mozilla Firefox.

![image](https://user-images.githubusercontent.com/344066/43362169-b7310d18-9315-11e8-9b5b-11dd8689e95f.png)

I have added an orange rectangle with rounded corners to help you understand what I mean.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

It occupies 2 rows cause the content is long.

What seems to be the problem?

Thanks.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Would you be able to make the "TOYS & COLLECTIBLES" occupy only 1 row?

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply!

OK!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Re-aranging elements to resolve 111 coincidentally resolved this issue.

(1) zent repo 76bb9728f9897ecd6c20af2098a4741b65d9e685

(2) pull request: https://github.com/usbong/UsbongStore/pull/112

Kindly check if result is ok:

![children](https://user-images.githubusercontent.com/8021327/43381183-6c4f69ec-9406-11e8-8a0d-0e64c493afc7.png)

Afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, I can confirm that your solution
has indeed also resolved this issue.

This case is now closed.

Thank you.

Peace,
Mike
