### ISSUE TITLE
Mobile Responsiveness: In Merchant page, header text, e.g. "Children's Books", does not occupy only 1 line

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#111]
Hi Zent,
I hope you are doing well.

I noticed that in the Merchant page, the header text for the following does not occupy only 1 line.

1) Children's Books

![image](https://user-images.githubusercontent.com/344066/43362129-b8f5ef20-9314-11e8-87bb-4fb8a048c2e2.png)

2) Miscellaneous Items

![image](https://user-images.githubusercontent.com/344066/43362138-ff067002-9314-11e8-9ba6-72f6aadba4fd.png)

This occurs both in Google Chrome and Mozilla Firefox.

What could be the probable cause?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I resolved this in:

(1) zent repo 76bb9728f9897ecd6c20af2098a4741b65d9e685

(2) pull request: https://github.com/usbong/UsbongStore/pull/112

![children](https://user-images.githubusercontent.com/8021327/43381137-4157b4b0-9406-11e8-925c-0449401d2b47.png)

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, I can confirm that you've 
indeed resolved this issue.

This case is now closed.

Thank you.

Peace,
Mike
