### ISSUE TITLE
Mobile Responsiveness: in Merchant page, product items do not automatically re-align

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#114]
Hi Zent,
I hope you are doing well.

I noticed that when I do the following, the product items do not automatically re-align.

1) From the Merchants page, i.e. `.../b/merchants`, click the "MOSC" Merchant logo.
2) There are product items, e.g. "Cane Aluminum (Local Non-adjustable)", whose "...[Free Delivery]" is not clearly visible.
--> This is due to its overlapping with the product item image below it.

I've found that the way to resolve this is to do the following steps:
1) Minimize the size of the browser window.
2) Maximize the size of the browser window.

Would you be able to offer a solution, so that the customer shouldn't have to do these steps?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike,

(1) I cant seem to recreate the problem (firefox and chrome).

![screenshot-2018-8-2 usbong store](https://user-images.githubusercontent.com/8021327/43560089-7f61b276-9643-11e8-8381-4ecd419f08cb.png)

Note: I came from https://store.usbong.ph/index.php/b/merchants

(2) Can you send me a screen shot of what you are seeing?

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

(1) The steps to replicate it seems rather peculiar.
--> I've only been able to replicate it using Google Chrome.
--> I'll notify you if I can provide you the exact steps for your debugging purposes.

(2) Here are the screenshots, as you requested.
a) 
![image](https://user-images.githubusercontent.com/344066/43572092-362e183c-9671-11e8-9b1a-1780942ae7b3.png)

b) 
![image](https://user-images.githubusercontent.com/344066/43572126-4eb90c86-9671-11e8-98b9-c0c104ab3f99.png)

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I tried several times again to recreate it in chrome. Unfortunately no luck.

(1) When you figure out how to recreate it, kindly inform me.

(2) Could you also try recreating it with the chrome console tab activated?

![console](https://user-images.githubusercontent.com/8021327/43573208-c8e48272-9673-11e8-8e0c-18f1697bc7cb.png)

     If some js errors come up on the console tab for assets/b/common.js, please inform me and maybe we can trace the problem.

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

(1) OK. I can replicate/recreate it, but the exact steps are not consistent.

(2) Yes, I've also attempted to replicate the bug with the Chrome Console tab activated.
--> Unfortunately, I haven't successfully replicated it with the tab activated.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Copy.

Would u have more tips to recreate other than coming from.merchant page?

If yes, i ll try recreating it again.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

The cause of the bug is likely due to the mobile responsiveness feature, 
which automatically realigns the product items.

Therefore, the bug may be caused by 
the adverse effect of moving 
from a page that is not mobile responsive
to one that is mobile responsive.

May I kindly ask if you've done the following to replicate it?
1) Hide the browser window.
2) Restore the browser window.
3) Create a new tab.
4) Enter the Usbong Store address, i.e. front page, on your local server/machine.
5) Click the "Medical" category.
6) Click the first or top-left product item, i.e. Back Support (Large).
7) Click the "MOSC" Merchant logo.
8) Click the "MOSC" Merchant logo again.
9) Click the "Usbong Specialty Bookstore" Merchant logo.
10) Click the "TOYS & COLLECTIBLES" category beneath the Usbong Specialty Bookstore Merchant logo.

I was able to replicate it using these steps.
I did not activate the Chrome Console tab.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

On Sat, Aug 4, 2018, 9:30 AM Masarap Mabuhay, <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> The cause of the bug is likely due to the mobile responsiveness feature,
> which automatically realigns the product items.
>
> Therefore, the bug may be caused by
> the adverse effect of moving
> from a page that is not mobile responsive
> to one that is mobile responsive.
>
It s unlikely cause the resources used are separated by page.

> May I kindly ask if you've done the following to replicate it?
>
What an odd list of steps....

Have not tried it. Let me try this afternoon.

Have a good day ahead!  😊

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Your observation about the oddity of the steps helped me realize that the issue may be caused by my using Google Chrome with too many tabs, i.e. 20 or so.

Perhaps, similar to when software do not have sufficient hard disk space, memory, and even electrical power coming from the computer/device's battery, they behave in unexpected ways.

Having said this, please tell me if you agree with me that we can now close this issue.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I followed the steps you sent and was still not able to recreate the
problem.

I also tried opening 20 tabs and following the steps again. Still could not
recreate.

Perhaps it was just a corner case browser glitch like you said.

Kindly close the issue.

Although in the future when we encounter it again and have more insights on
it, we can re-open.

Thank you!

**Comment by masarapmabuhay** [comment]
OK, Zent! I have closed the issue.

Thank you.

Peace,
Mike
