### ISSUE TITLE
W Pages - Add to Cart: Can't Use Backspace in Firefox

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#116]
Good Day Mike,

(1) In w pages > add to cart, the backspace doesn't seem to work when using firefox.

![screenshot-2018-9-14 usbong store 1](https://user-images.githubusercontent.com/8021327/45527823-25ebd480-b810-11e8-9d6b-17798e65617a.png)

(2) Chrome looks ok.

(3) Could you check if you can recreate the problem on your end?

Url: https://store.usbong.ph/index.php/w/A-Brief-History-of-Time-Stephen-Hawking/233

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for notifying me of this issue.

I can reproduce the problem on Mozilla Firefox.

Moreover, on Microsoft Edge, 
the problem doesn't occur.

Let me see what I can do.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Okly dokly!

I'll wait for resolution on non mobile responsive page and reflect it on mobile responsive page.

Most likely, it has something to do with this line:

FIle: views/w.php

Line: 

`
onKeyPress="if(this.value.length==2) {return false;} if(parseInt(this.value)<1) { this.value='1'; return false;}"
`

But I'm not 100% sure.

Happy sunday!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! I'll notify you as soon as I am able to resolve the issue.

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
I hope you are doing well.

I made time today to address the issue you raised.
I've resolved it in my newest commit and push: https://github.com/usbong/UsbongStore/commit/e6dfb580c63056fcfe9872352f6d3565562ff41c

If the issue remains on your end, please simply re-open this issue.

Thank you.

Peace,
Mike
p.s. It took me more than a month to return to this issue. I've been concentrating the 80% of my working time on Usbong's main revenue stream, which comes from providing computing/IT services to our partner clinics. The remaining 20%, I've been establishing partnerships with schools, stores, suppliers, and other service providers in Marikina City and outward.

**Comment by zent-lim** [comment]
Thanks for the update Mike.

(1) I have verified the fix for usbong_store/application/views/w_v2.php

(2) usbong_store/application/views/w.php was not updated though.

      Should it also be updated?

Thank you.

P.S.
Cool! Best of luck in this new direction. :)

**Comment by masarapmabuhay** [comment]
Hi Zent,
I hope you are doing well.

I have resolve the issue in the product item page of the Non-mobile responsive version.
This is the link to my newest commit and push: https://github.com/usbong/UsbongStore/commit/ae4bb06e2e5fde36bfd176b001d232ae7f201e58

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Good day Mike,

Update looks good.

Thank you!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK!

Peace,
Mike
