### ISSUE TITLE
Mobile Responsiveness: Misaligned text, fields, and button on the "Create New Account" page

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#119]
Hi Zent,
I hope you are doing well.

May I kindly verify with you
if our repository on GitHub
already has your newest version
of the Usbong Store code?

This is what I see on Firefox Quantum 62.0 (64-bit):

![image](https://user-images.githubusercontent.com/344066/45927858-9e6b3780-bf6c-11e8-821f-63f9bee24fcb.png)

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have reverified the code 
on my local Windows server.

(1) I am already using the newest version from our Usbong Store repository on GitHub.

(2) Yes, the mobile responsiveness switch is set to TRUE.

(3) Yes, the core controller is the newest version.

The behaviour appears to be the same for both:
1) Firefox Quantum 62.0 (64-bit)
2) Microsoft Edge 40.15063.674.0 and Microsoft EdgeHTML 15.15063

Thank you.

Peace,
Mike
p.s. You seem to have not attached the file/screenshot you mention in your reply.

**Comment by zent-lim** [comment]
Hi Mike,

(1) Let me check in my env.

(2) Sorry. Here's the content of git log -10 or git log -15. The entry
should appear towards the bottom:

commit 535d49a8c113d1ec27f042df067bb12ae671fa30
Author: Zent Lim <zentlim@gmail.com>
Date:   Wed Sep 12 14:16:15 2018 +0800
Added mobile responsive version of account/create.

Evening!

**Comment by zent-lim** [comment]
Good Day Mike,

(1) The commit below seem to have damaged the repo.

      commit fedb5d3b9e8897d8bf5c955e9ae17bfce86b04f4

      Author: Michael B. Syson <masarapmabuhay@gmail.com>

      Date:   Sun Sep 16 20:30:19 2018 +0800

      Note: +fixed: when Mobile Responsiveness setting is set to TRUE,
incorrect product item count displayed on the cart icon of Mobile
Responsive pages

(2) Particularly, core controller function initHeader() was damaged.

     Damaged Version:
https://github.com/usbong/UsbongStore/blob/fedb5d3b9e8897d8bf5c955e9ae17bfce86b04f4/usbong_store/application/core/MY_Controller.php

     Stable Version (1 commit earlier of Damaged Version):
https://github.com/usbong/UsbongStore/blob/daffa9c467f149d8b16bbe9917e75e33edfefbae/usbong_store/application/core/MY_Controller.php

(3) Please see the url in Stable Version.

    Lines 144 to 176 in Stable Version is incomplete in Damaged Version
(lines 127 to 142).

    Around 10 lines disappeared in Damaged Version.

Have a good evening ahead.

**Comment by zent-lim** [comment]
Morning Mike,

Thank you for the update.

(1) Firefox looks good in the  latest push.

(2) Chrome looks ok also.

![chromexs](https://user-images.githubusercontent.com/8021327/46114780-b241c280-c226-11e8-86d8-6acbf9d73a40.png)

(3) Currently, I dont have the tech stack to run Windows Edge.

      (a) Can we schedule a work meet after October 9? 

      (b) Based on quirk searches though, Edge seem to be buggy (so even if we meet, there s a decent chance we cant fix it):

            https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13962174/

            https://github.com/twbs/bootstrap/issues/25309

            https://stackoverflow.com/questions/37683629/ie-ms-edge-links-in-bootstrap-col-not-working-on-page-load

       (c) Additionally, user base seem small (but not certain):

            https://www.computerworld.com/article/3242165/microsoft-windows/microsofts-edge-browser-is-in-serious-trouble.html 

Thanks.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

(1) OK.

(2) OK.

(3) 
(a) Yes, we can schedule a meetup after Oct. 9.
(b) OK.
(c) OK.

--> I realized that we'll also have to verify whether the issue occurs on the Safari browser. 

**Action Item:**
1) Verify if the issue also occurs on the Safari browser
--> Owner: Mike
--> Finish: Sept. 29, 2018 (Sat)

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Okly dokly Mike,

Catch up w u when i get back after oct 9. :)

Thanks! :)

**Comment by zent-lim** [comment]
Hi Mike,

Thank you for the info.

No luck on my end finding a way to run safari.

The closest one was an onld version, but the thread below says it wont run
anymore:
https://askubuntu.com/questions/585209/opera-and-safari-installation

Let's add this agenda to our work session after OCt 9.

Thank you!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply!

Let me now reply to your reply 
with an OK and a thank you!

Peace,
Mike
p.s. it took me 3 days to reply to you though, which isn't our usual standard of 2 business days.
