### ISSUE TITLE
Mobile Responsiveness: Misaligned text, fields, and button on the "Sign In" page

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#120]
Hi Zent,
I hope you are doing well.

I have verified that the issue we encountered in https://github.com/usbong/UsbongStore/issues/119
occurs similarly with the "Sign In" page
using also the following browsers:

1) Microsoft Edge 40.15063.674.0 and Microsoft EdgeHTML 15.15063

![image](https://user-images.githubusercontent.com/344066/46580577-fff5d080-ca59-11e8-92da-534f549ce009.png)

2) Safari browser (Version 11.1.2 (12605.3.8.1))

![image](https://user-images.githubusercontent.com/344066/46580543-7ba34d80-ca59-11e8-9279-5e3193854bb1.png)

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

Copy.

Have a good evening ahead. 😊

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! Do you agree to meet 
this Oct 11, 2018 (Thursday),
9 AM~11 AM at Usbong HQ?

**Agenda/Plan of Action:**
1) Resolve the issue on the Safari browser.
--> **Owners:** Zent and Mike
--> **Finish:** Oct. 11, 2018 (Thursday)

**Steps:**
1) Connect your laptop with the newest version of the Usbong Store to the router.
2) Connect my MacBook Pro to the router.
3) Verify whether the issue is resolved on the Safari browser using my MacBook Pro.
4) Debug the Usbong Store on your laptop if the issue persists.
5) Repeat step 3).

I have a router and two (2) LAN/RJ-45 cables (straight).

Please tell if we'll need anything else.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

Back at manila. :)

I ll be at the family store on oct 11. (Sorry for the inconvenience.)

Would it be ok to schedule the coming week? If yes, may i know what day and
time is convenient for u?

So far, 15, 16, 17, 19 are currently open.

P.s.
Have mochi for you from Japan. 😁

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Welcome home!

OK! Do you agree that we schedule 
our Agenda/Action Plan as follows?

**Agenda/Action Plan**
1. Resolve the issue on the Safari browser.
--> **Owners:** Zent and Mike
--> **Finish:** Oct. 15, 2018 (Monday)
--> **Date:** Oct. 15, 2018 (Monday)
--> **Time:** 9 AM~11 AM
--> **Place:** Usbong HQ
--> **Requirements:** 
--> a) MacBook Pro
--> b) iPad
--> c) Linux-based laptop with the Usbong Store (newest version)
--> d) router
--> e) one (1) LAN/RJ-45 cable (straight)

2) Resolve the issue on the Microsoft Edge browser.
--> **Owners:** Zent and Mike
--> **Finish:** Oct. 16, 2018 (Tuesday)
--> **Date:** Oct. 16, 2018 (Tuesday)
--> **Time:** 9 AM~11 AM
--> **Place:** Usbong HQ
--> **Requirements:**
--> a) Windows-based laptop
--> b) Linux-based laptop with the Usbong Store (newest version)
--> c) router
--> d) two (2) LAN/RJ-45 cables (straight)

Thank you.

Peace,
Mike
p.s. OK!

**Comment by zent-lim** [comment]
Morning Mike!

Can we reduce it to one visit w longer hours? (It might be a 1.5 to 2 hour
trip from here to marikina.)

If yes, monday 9 a.m. onwards works.

Thank you!

P.s.
Not familiar w the network set up u re planning. Kindly show me when we
meet.

**Comment by zent-lim** [comment]
Okly dokly Mike! See you monday! ☺

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply!

OK! Please do make sure to also update 
your Linux-based laptop to the newest 
version of the Usbong Store.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) No problem re update. My env is now in:

    commit aa63319a4d040a547394abd04e7aaaf584f2f4ac

    Author: Michael B. Syson <masarapmabuhay@gmail.com>

    Date:   Sun Oct 14 16:23:17 2018 +0800

        +updated: the background color we use for the navigation bar for
the product categories/types row
        --> It now uses the same one we used previously, i.e. coffee
cream/pearly sand.
        --> I do agree, however, that concentrating with the local
community as a start to value how to count effectively and efficiently
should enable us to grow and eventually expand outward.
        --> work-in-progress

(2) Additionally, we can easily switch between versions using git checkout
command.

See you tomorrow!

<------Debug Guide------>

(1) Check if stable version has problem in safari

    commit 1dd2127625c4423acf8b8bfc422c3a78507eda13
    Author: Zent Lim <zentlim@gmail.com>
    Date:   Fri Sep 14 16:28:08 2018 +0800

        Added popup for mobile responsive version of w pages.

(2) If stable version has no problem with safari, check difference

    git diff 1dd2127625c4423acf8b8bfc422c3a78507eda13
aa63319a4d040a547394abd04e7aaaf584f2f4ac

(3) If stable version has problem with safari, check css

    command: command + option + i

    ref:
https://apple.stackexchange.com/questions/139767/inspect-element-in-safari

    note: advance > show developer menu in menu bar

    (a) check usbong_store/application/views/templates/style_v2.php >
.login-and-create > margin 0 auto

    (b) check browser bug matches in url below

        https://getbootstrap.com/docs/3.3/browser-bugs/

**Comment by zent-lim** [comment]
Hi Mike,

As we have investigated, the problem is not browser related.

Live server files are not in sync with latest master repo below:

commit aa63319a4d040a547394abd04e7aaaf584f2f4ac

Author: Michael B. Syson <masarapmabuhay@gmail.com>

Date:   Sun Oct 14 16:23:17 2018 +0800

(1) Below are files that are not in sync in live server (that has impact on view):

    - application/views/templates/header_v2.php

    - application/views/templates/style_v2.php

(2) Below are other files in live server (not related to current problem) that are not in sync with master repo:

    - application/helpers/MY_url_helper.php

    - application/views/b/merchants.php

    - application/views/templates/footer_v2.php

Let's try to sync (1) above.

Thanks!

**Comment by zent-lim** [comment]
Hi Mike,

(1) Thank for updating live server and confirming that the priblem is fixed.

(2) The ff are not yet in live server:

      - application/helpers/MY_url_helper.php

      - application/views/b/merchants.php

Good afternoon!

**Comment by zent-lim** [comment]
Hi Mike,

(1) Thank for updating live server again.

(2) The ff are not yet in live server:

  - application/views/b/merchants.php

Good afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for coming 
to the Usbong HQ,
here in Marikina City.

OK! 

I have set the Mobile Responsiveness switch 
back to FALSE on the live/production server.

I shall continue to verify 
your deliverables
based on our Gantt Chart.

Thank you.

Peace,
Mike
