### ISSUE TITLE
Mobile Responsiveness: in product item page, after clicking "ADD TO CART", font size and color of text in pop-up window is smaller and of a lighter shade

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#123]
Hi Zent,
I hope you are doing well.

I am presently doing QA (Quality Assurance) of **Usbong Store (Mobile Responsiveness) Phase 3: Milestone 4: w**.

**Observation:**
In the product item page, after clicking "ADD TO CART", the font size and color of the text in the pop-up window is smaller and of a lighter shade.

1) **Mobile Responsive version:**
![image](https://user-images.githubusercontent.com/344066/47402432-1ef1a380-d778-11e8-8f45-1628b3cbd11f.png)

2) **Non-mobile Responsive version:**
![image](https://user-images.githubusercontent.com/344066/47402502-8576c180-d778-11e8-8fee-1e576e988727.png)

Would you be able to update the font size and color to match with the **Non-mobile Responsive version**'s?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Good Day Mike,

This was done intentionally as the new version is aesthetically better in
my opinion.

Are you sure you'd like to use the font size and font color from the old
version?

If yes, no problem.

I would simply like to double confirm.

Have a good day ahead.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, let's use the font size and color in the **Non-mobile responsive version**.

The larger font size and the darker shade make it easier for me to read the text.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Thank you for confirming the direction.

(1) I executed your request in:

commit 77debcc0d1ebdb376af97e831296b1f133333f18

Author: Zent Lim <zentlim@gmail.com>

Date:   Thu Oct 25 15:58:03 2018 +0800

Note: Resolved issue 123.

![diff](https://user-images.githubusercontent.com/8021327/47485146-17adc100-d870-11e8-8802-95342b4e1010.jpg)

(2) I sent a pull request in:

https://github.com/usbong/UsbongStore/pull/125

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
I hope you are doing well.

OK. I have verified your update.

I increased the font size we use for the product item name.

![image](https://user-images.githubusercontent.com/344066/47598721-e568a480-d9d2-11e8-884f-aadbd7fb7929.png)

I have committed and pushed my update here: https://github.com/usbong/UsbongStore/commit/e1fd263f6e709f6985933add86564c28844159a9

This issue is now closed.

If you disagree, please simply re-open it.

Thank you.

Peace,
Mike
