### ISSUE TITLE
Auto-email: Would it be possible to select a product item without having the browser refresh itself? 

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#14]
Hi Zent,
Would it be possible in auto-email to select a product item without having the browser refresh itself? 

Perhaps this can be added in Phase 2?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Surely!

I'll add that to the phase 2 estimate due next Wednesday.

Evening!

**Comment by masarapmabuhay** [comment]
OK, Zent!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I resolved this in commit: 410e96359e823f341f16d14033117b41cc433756

Pull Request:
https://github.com/usbong/UsbongStore/pull/30

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the commit.

I've checked your update on dev (Ubuntu) in VirtualBox.
It seems that you were indeed able to resolve the issue.

This case is now closed.

Thank you.

Peace,
Mike
