### ISSUE TITLE
Auto-email: Subject header in DB not used

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#16]
Hi Zent,
I was looking at the email that auto-email sent.

It seems that the subject header used is not the one that I set in the auto-email interface.

Would you know what could the probable cause be?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Please see the answer I posted on Issue 15 on 2017-10-19:
https://github.com/usbong/UsbongStore/issues/15

Thanks!

P.S.
For the mean time, I will try to recreate your problem using the ff:

(1) source code
Commit: 1970411de9877a579144953c85be9ed10e9ae0aa
Note: fixed: overwritten/removed auto-email files during my last commit to
GitHub

(2) sql: v04

**Comment by zent-lim** [comment]
Hi MIke,

This is not a bug.

We have verified that the email sent in your test scenario was correct.

It just so happened that the queue logic prioritized an older email that needed to be sent out.

Good afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the messages.

OK!

Peace,
Mike
--
Usbong: Uplifting Human Lives
*www.usbong.ph <http://www.usbong.ph/>*
--
Michael B. Syson
