### ISSUE TITLE
Auto Email Cron Script Code Clean Up Bug

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#18]
Hi Mike,

Please check the file below:
UsbongStore/usbong_store/application/views/auto-email/email_frame_simple_template.php

--------------------------------
PROBLEM
--------------------------------

(1) $header['apps'] was reduced from 10 elements to 5 elements in code clean up.

(2) Line 165 to 173 was commented out to remove displaying unused index. It was commented out using "html group comment brackets".

(3) The html was commented out, but the php inside the comment still runs despite the "comment out".

(4) In my environment this resulted into the following notice when kicking the cron script:
      (a) File: UsbongStore/usbong_store/application/logs/log-2017-XX-XX.php
      (b) Error:

ERROR - 2017-10-20 19:30:31 --> Severity: Notice --> Undefined offset: 5 /var/www/html/UsbongStore/usbong_store/application/views/auto-email/email_frame_simple_template.php 168

(5) The NOTICE is seen in log file using log_threshold = 4.
      (a) File: application/config/config.php
      (b) Field: $config['log_threshold'] = 4

--------------------------------
RECOMMENDATION:
--------------------------------

The code still continues execution. But it does not look safe.

To avoid complications, please delete unused code instead.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the feedback.

I have removed the pertinent lines of code, and have committed the updated code to our GitHub repo.

The errors you encountered should now be fixed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I have verified the fix in:
af2ec9e3ceb65b8e09ecaec0b11c03d09e8d8f77

Updated log no longer contains errors:
INFO - 2017-10-20 22:02:54 --> AutoEmail: SETTING QUEUE to ACTIVE:
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> auto_email_schedule_id = 3
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> customer_ids           = 1
to 1
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> max_send               = 20
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> protocol               =
smtp
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> smtp_host              =
smtp.gmail.com
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> smtp_user              =
zentlim@gmail.com
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> smtp_crypto            = ssl
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> smtp_port              = 465
INFO - 2017-10-20 22:02:54 --> AutoEmail:  |--> mailpath               =
/usr/sbin/sendmail
INFO - 2017-10-20 22:02:54 --> AutoEmail: Sending email to
zent_lim@yahoo.com
INFO - 2017-10-20 22:02:54 --> File loaded:
/var/www/html/UsbongStore/usbong_store/application/views/auto-email/email_frame_simple_template.php
INFO - 2017-10-20 22:02:56 --> Language file loaded:
language/english/email_lang.php
INFO - 2017-10-20 22:02:59 --> AutoEmail: QUEUE SET to DONE.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the feedback.

Peace,
Mike
