### ISSUE TITLE
Auto-email: Database Error when Creating a New Batch

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#23]
Hi Zent,
I encounter the following error after I do `Create New Batch`.

```
Error Number: 1452

Cannot add or update a child row: a foreign key constraint fails (`usbong_store`.`auto_email_schedule`, CONSTRAINT `auto_email_schedule_fk_end_customer_id` FOREIGN KEY (`end_customer_id`) REFERENCES `customer` (`customer_id`) ON UPDATE CASCADE)

INSERT INTO `auto_email_schedule` (`auto_email_id`, `start_customer_id`, `end_customer_id`, `start_datetime`, `status`) VALUES ('3', '1', '30', '2017-11-06 11:08:49', 'QUEUED')

Filename: models/auto-email/Auto_Email_Schedule_Model.php

Line Number: 254
```
May I ask what the probable cause could be?

Peace,
Mike

**Comment by zent-lim** [comment]
Hi MIke,

Please check this thread:
https://github.com/usbong/UsbongStore/issues/20

There are two causes.

Please look for two messages from me:
(1) "Did this error occurred when you tried to import v05 sql?"
(2) "Let's back track a bit."

Have a good evening ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) No, I've already imported v05 sql.
2) OK.

Yes, the error appears when the Start Customer ID and the End Customer ID are not available in the DB.

Perhaps, in the next phase of auto-email, we can add a more helpful error message such that even non-programmers can quickly identify the cause.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Kindy double check the links i gave to you.

Particularly the one with "let s back track a bit".

That error should have been caught and the logic i wrote should have
returned a warning message.

Thanks!

P.s.
Sorry. Typing on mobile and unable to place the exact links.

**Comment by zent-lim** [comment]
Hi Mike,

(1) Pls look for a message from me regarding your database config file on
the thread "let s backtrack a bit".

(2) Pls check a field called "debug" and let me know what it contains in
your production environment (not local, production).

(3) basically this problem has already happened before in ur local server
and we have already confirmed that the db config you are using has a faulty
setting.

Thanks!

**Comment by zent-lim** [comment]
Hi Mike,

Got access to laptop.

Here's a synopsis of our past threads:

(1) Open file below:

     UsbongStore/usbong_store/application/config/database.php

(2) Check that field "db_debug" evaluates to FALSE

     RECOMMENDED VALUE FOR PRODUCTION AND LOCAL:
     'db_debug' => (ENVIRONMENT !== 'production'),

     NOTE:
     (a) There is an ! before ==

     (b) The line of code above is same as the code below if run in
production:
          'db_debug' => FALSE

     (c) The line of code above is same as the code below if run in local:
          'db_debug' => TRUE

(3) Below is expected behavior:

     (a) Set it correctly in PRODUCTION and try to recreate the scenario
end id = 30. A warning message should be flagged and the code should not
crash.

    (b) Set it to correctly in LOCAL and try to recreate the scenario end
id = 30. The code crashes and shows the SQL error immediately for faster
debugging.

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I've checked `...usbong_store/application/config/database.php`.
It is already set to the following:

`  'db_debug' => (ENVIRONMENT !== 'production'),`

However, given this, the error occurs.

Thank you for your kindness.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

Thanks for checking.

I'll check the following next.

I suspect it's the following settings in the file below:

File: /var/www/html/UsbongStore/usbong_store/index.php

Line of Code 1:
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] :
'development');

Line of Code 2:
        case 'production':
                ini_set('display_errors', 0);
                error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED &
~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED);
        break;

Have a good evening ahead!

**Comment by zent-lim** [comment]
Evening Mike,

==========
UPDATE
==========

I was able to recreate your error.

In my environment, the line below evaluated to 'development':

File: /var/www/html/UsbongStore/usbong_store/index.php

Line of Code:
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] :
'development');

==========
SOLUTION
==========

Please pick a solution that best fits your use case.

(1) Solution 01:

      (a) Change the line of code above to:
            define('ENVIRONMENT', 'production');

      (b) Warning: since you've been running your production server in
development mode, I am unsure if changing it to production mode will have
negative impact on your older features.

(2) Solution 02:

     (a) Update usbong_store/application/config/database.php.

Original Code:

'db_debug' => (ENVIRONMENT !== 'production'),

New Code:
'db_debug' => FALSE,

    (b) Note: Since your 'ENVIRONMENT' field is not set correctly, you
can't use it set field 'db_debug'. So simply set it to FALSE on production.

==========
DESIRED BEHAVIOR
==========

Please see attached file for desired behavior on error handling.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK. I have set the following: `'db_debug' => FALSE,`

It seems to have resolved the issue.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Awesome!

When things are not so busy on ur end, pls file a ticket on whatever
problems u re having w cron. Let s take a look see.

Thanks!

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike
