### ISSUE TITLE
Models Return Fatal Error: Call to a member function result_array() on a non-object

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#25]
Hi Mike,

(1) I sync my fork to usbong_store latest master code:

commit 8deb5833cb876f8e7f324516a569bcfc8f9afa17
Author: Michael Syson <masarapmabuhay@gmail.com>
Date:   Mon Nov 20 19:36:24 2017 +0800

    +added: more product items from Mitch Albom, e.g. "have a little faith", "the five people you meet in heaven", and "for one more day"
    --> I no longer remember the story of "for one more day", but I do remember crying after finishing reading it

(2) I encountered the problem below upon opening home page (store.usbong.ph):

A PHP Error was encountered

Severity: Error

Message: Call to a member function result_array() on a non-object

Filename: models/Books_Model.php

Line Number: 17

REQUEST:

(1) I tried investigating but didn't get far.
      (a) I checked if product table has data. It looks ok.
      (b) I looked at model code and it also looks ok.

(2) Would you have an idea what causes this error?

Thank you.

**Comment by zent-lim** [comment]
Hi MIke,

I think my sql is old.

Could you advise which of the sql in the link below I should use to re-init my database?

https://github.com/usbong/UsbongStoreApp/tree/master/db

Thank you!

**Comment by zent-lim** [comment]
Hi Mike,

(1) I used this sql (seemed like the latest):
https://github.com/usbong/UsbongStoreApp/blob/master/db/usbong_store20171114.sql

(2) I turned on db debug mode.

(3) But problem persists.

Here is new error that might narrow things down:

Unknown column 'quantity_sold' in 'field list'

SELECT `product_id`, `product_type_id`, `name`, `author`, `price`, `previous_price`, `quantity_in_stock`, `product_view_num`, `quantity_sold` FROM `product` WHERE `product_type_id` = '2' ORDER BY `name`

Filename: models/Books_Model.php

I'll wait for your advise on SQL install.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the messages.

Here is the link to the updated SQL DB:
https://github.com/usbong/UsbongStoreApp/blob/master/db/usbong_store20171121.sql

It should resolve the issues that you've encountered.

Please never hesitate to let me know if the problem persists.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Thanks Mike!

This resolved the problem. Evening!

**Comment by masarapmabuhay** [comment]
Thank you, Zent, for the feedback.

Peace,
Mike
