### ISSUE TITLE
Product Url Scheme Has Trailing "-"

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#3]
--------------
PROBLEM
--------------

The home page generates product url using author field.

However some items are not books and don't have authors.

Below are examples.

(1) Ketchup

https://store.usbong.ph/index.php/w/Heinz-Tomato-Ketchup-/128

Please see "-" after "Ketchup".

(2) Coffee

https://store.usbong.ph/index.php/w/UCC-Coffee-Rich-Blend-/29

Please see "-" after "Blend".

In cases where there is no author, an trailing "-" is seen.

--------------
TEMP FIX
--------------

As consulted with Mike, the strategy should be maintained for now.

A new function in the file below will use the same logic:

File: UsbongStore/usbong_store/application/helpers/MY_url_helper.php

Function: create_product_url()

**Comment by masarapmabuhay** [comment]
Thank you! Peace.
