### ISSUE TITLE
Auto-email: "Warning! Data is invalid." upon product item selection

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#31]
Hi Zent,
I was creating a new auto-email to check  your "Milestone 3: Cron Script Backward Compatibility Update".

As I was selecting the 4th product item, the following message appeared:

> "Warning! Data is invalid."

<img width="960" alt="usbongstoreautoemaildatainvalid20171204" src="https://user-images.githubusercontent.com/344066/33537863-036a5b4e-d8f9-11e7-8dfd-735ad95513ff.png">

What could be the probable cause?

Thank you.

Peace,
Mike
p.s. please let me know if you are unable to view the image I attached.

**Comment by zent-lim** [comment]
AfternooN Mike!

This warning is issued when an external incompatible entity tries to access
the ajax controllers.

In this case however, that scenario is unlikely.

I ll investigate further this evening by trying ro create an email with
"mangga" as search.

Could u send me a link to the most updated sql file of live server so i can
recreate this issue?

Thanks lots!

**Comment by masarapmabuhay** [comment]
Hi Zent,
OK! I have emailed you the cleaned-up version
of our prod's newest SQL DB.

Please let me know if you need anything else.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Thanks for the SQL Mike!

I was able to recreate the problem.

(1) It's a nuisance between Chrome and Firefox.

(2) The add and remove button html is structured as follows:

<button data-toggle="tooltip" data-placement="left" data-product-id="44"
title="Select" name="submit_button" type="submit" class="btn btn-success
btn-xs">
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
</button>

(3) When you click the button in firefox, the button div is triggered. When
you click the button in chrome, the span div is triggered.

(4) The code I wrote assumes that button div is triggered resulting to
misparsed DOM when the action is done in chrome (where span is triggered).

I will update code to support both use cases.

Evening!

**Comment by zent-lim** [comment]
Evening Mike,

I submitted a pull request to fix this issue:
https://github.com/usbong/UsbongStore/pull/32

Kindly verify the bug fix.

Have a good evening ahead!

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you.

I have merged your pull request.
Let me verify if it indeed resolved the issue.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
This issue is now closed.

Thank you.

Peace,
Mike
