### ISSUE TITLE
Auto-email: Email preview doesn't work

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#33]
Hi Zent,
I encountered a 404 page error after clicking the preview icon in the Action column, in:
https://store.usbong.ph/auto-email.

I have already updated the code in prod to use your newest pull request.

Would you be able to offer advice on its probable cause and how we may be able to resolve this issue?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Kindly check if the lines below are present in prod.

(a) File: UsbongStore/usbong_store/application/routes.php

(b) Lines:
$route['auto-email/preview/(:num)']                =
'auto-email/administer/preview/$1';
$route['auto-email/unsubscribe/(:any)']            =
'auto-email/administer/unsubscribe/$1';

(c) Reference Email: Auto Email Phase 2 Milestone 1, 2, 3, 5

<-----snip----->

    (c) Notes:
        (i) I updated common file config/route.php for new routes.
        (ii) I updated common file config/config.php and set field
encryption_key for unsubscribe feature.

<-----snip----->

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have checked prod, and did not find the lines you indicated.
I have updated `...application/routes.php` accordingly.

The issue is now resolved.

Thank you.

Peace,
Mike
