### ISSUE TITLE
Auto-email: Font type in auto-email preview is different from the actual email sent 

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#35]
Hi Zent,
I was checking auto-email preview, and I noticed that the font type it uses is different from the one that is actually used in the email auto-email sends.

Unless I'm mistaken, the font type should be Arial.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

Let me check this when i get access to laptop.

Evening!

**Comment by zent-lim** [comment]
Hi Mike,

INVESTIGATION:

Prior to this issue, the email template we used had no font set.

It just so happened that arial was the default font used by gmail and we
saw the email as arial.

I updated the template to make arial the default font.

If arial is not supported by the browser, it will fall back to sans-serif.

The combination of arial then sans-serif was chosen based on gmail default
behavior. We can change it as you wish.

RESOLUTION:

I sent a pull request resolving this problem:

https://github.com/usbong/UsbongStore/pull/36

Have a good evening ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
I've verified your pull request.

Please check my findings here:
https://github.com/usbong/UsbongStore/pull/36

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Okly dokly Mike,

I replied to ticket.

Happy weekend!

**Comment by masarapmabuhay** [comment]
Thank you, Zent!

Peace,
Mike
