### ISSUE TITLE
Auto-email: Is there a way to edit the Subject, etc once the email has been added to the list?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#37]
Hi Zent,
Is there a way to edit the Subject, etc once the email has been added to the list of auto-emails to kick?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Currently, there is no edit feature.

In case it is really needed, you may directly edit table auto_email. If
memory serves right, column subject.

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
OK! Thank you!

Peace,
Mike
