### ISSUE TITLE
Auto-email: Incorrect peso character in email

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#38]
Hi Zent,
I just sent an email blast using auto-email.

I added a peso character using its UTF-8 equivalent, `&#x20B1;`.

Unfortunately, when I received the email, the UTF-8 character remained as `&#x20B1;`.

I also used the peso symbol from MSWORD, but the details in the auto-email page showed `?`.

May I ask how we may be able to resolve this?

Thank you for your kindness.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

May i know Where the peso was placed? Was it the intro paragraph?

Thanks!

**Comment by zent-lim** [comment]
Hi Mike,

(1) I think it's subject line.

(2) It seems gmail encodes subject differently than body.

Please check your personal mail in cc for a shot where Peso rendered
correctly on body but not in subject.

I tried a few work around but none has worked so far.

https://tools.bluestatedigital.com/kb/article/how-to-encode-unicode-emojis-into-your-subject-line

https://tools.bluestatedigital.com/kb/subject-line-assistant

https://stackoverflow.com/questions/27695749/gmail-api-not-respecting-utf-encoding-in-subject

https://stackoverflow.com/questions/2722451/how-do-i-decode-mail-header-strings-with-their-encoding-type-in-them-in-php

(3) I'll investigate further.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) Yes, you are correct. It is in the subject line.
2) OK. I have email you a copy of the auto-email I sent.
3) OK.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Here are the changes that needs to be made to be able to fit your use case - allow peso in subject line.

STEPS:

(1) Please run the sql below in the server being used:

    ALTER TABLE auto_email_template CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE auto_email CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE auto_email_product CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE auto_email_schedule CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE auto_email_sent CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE auto_email_setting CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    ALTER TABLE auto_email_unsubscribe CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

    The sql above changes auto_email tables from latin1 default collation to utf8 utf8_unicode_ci collation.

    This allows you to save utf8 encoded characters (like ₱) in auto_email tables.

(2) To use ₱, you can do two things:

    (a) Use a keyboard with a peso sign

    (b) search the net for a peso sign, copy it, then paste it to the auto_email subject input box

          here is a good reference for a peso sign that you can copy and paste: http://www.fileformat.info/info/unicode/char/20b1/browsertest.htm

NOTES:

(1) latin1 default collation was used for auto_email to follow the original usbong database structure.

    But since now we have a use case that requires otherwise, I have changed all auto_email tables to use utf-8.

(2) I have also released v7 of mwb and sql to reflect the changes in STEPS - (1) above.

    But I recommend that you use the raw queries above instead so you won't have to re-install (delete, create) the auto_email tables.

    Commit: b877971bf73e8c989757aee954ae9cdb4977a79e

(3) Typing hex equivalent of Peso \&\#x20b1; in the email subject line will NOT work.

    When an email is sent from usbong app to gmail server, the subject line is sent as an ASCI encoded header and not as html.

    A more complicated encoding is used to be able to send UTF-8 characters on the subject line.

    To send out the subject "Irrationality Sale! Buy 2 Books, Up to ₱250 Off!", Usbong App must send a header structured below:

    =?UTF-8?Q?Irrationality=20Sale!=20?==?UTF-8?Q?Buy=202=20Bo?= =?UTF-8?Q?oks,=20Up=20to=20=E2=82=B1250=20Off?==?UTF-8?Q?!=20?=

(4) I havn't tried copying and pasting a peso sign from word to the auto_email input box, but I think it will now work because of the change in database collation.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Your solution resolved this issue.

Thank you.

Peace,
Mike
