### ISSUE TITLE
Updating Links of "Installing Product Management Feature" Wiki

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#41]
Hi Zent,
I'm reading the [Installing Product Management Feature](https://github.com/usbong/UsbongStore/wiki/Installing-Product-Management-Feature) Wiki.

1) I updated the Import New SQL URL:

Previous:
https://github.com/zent-lim/UsbongStore/blob/master/auto-email/product_table_add_external_url_and_show_v01.sql

New:
https://github.com/usbong/UsbongStore/blob/master/auto-email/product_table_add_external_url_and_show_v01.sql

I understand that the values for each of the SQL commands are the same?

2) May I ask if you pushed this commit to the official Usbong Store repository?

https://github.com/zent-lim/UsbongStore/commit/73e54fec50348705c6bb7b6a7d44410cc7d8b268

We've experienced developers leaving (usually suddenly), so it would be good to make sure that the code, etc would still be available on the Usbong repository.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) Yes, the two sql files are the same.

The link I placed used zent repo because the pull request was not yet
approved.

Hence the file was not available in usbong repo yet.

After you approved the pull request, the file should have made it to usbong
repo.

(2) Yes. The source code under zent-lim repo should have been merged to
usbong repo after you approved my pull request for milestone 1.

Have a good evening ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

(1) OK!

(2) OK. I was browsing through your pull requests, and please correct me if I'm wrong, the equivalent link of your commit, i.e. zent-lim/UsbongStore@73e54fe, is the following:

https://github.com/usbong/UsbongStore/pull/39/files

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Yes, that's correct.

When you look at the link below, you can click commit tab and it will show
which commits are included in this pull request.

https://github.com/usbong/UsbongStore/pull/39/files

Here is the link for the commits tab to the pull request:
https://github.com/usbong/UsbongStore/pull/39/commits

This pull request has 3 commits. One of which is the code you are
interested in - 73e54fe.

The other two seem old (from before Phase 3).

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have updated the [Installing Product Management Feature](https://github.com/usbong/UsbongStore/wiki/Installing-Product-Management-Feature) Wiki accordingly.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Thanks for updating Mike. 😊
