### ISSUE TITLE
Manage Product: "Image field is required" even after image upload

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#43]
Hi Zent,
I am now in Step 4.(f) of ["Installing Product Management Feature" Wiki](https://github.com/usbong/UsbongStore/wiki/Installing-Product-Management-Feature).

After I uploaded the following image (Usbong icon), an "Image field is required" message appeared.
https://avatars0.githubusercontent.com/u/17630584?s=200&v=4

May I ask what the minimum image dimensions are to make a successful image upload?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike (added your personal email for attachment),

I tried to recreate your problem.

I think its not a file size issue. It looks like file format.

Please use a jpeg.

After you choose a jpeg, it should look like this:


​
Then you should be able to move the image around and zoom in and out.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, you are correct.

`.png` is not accepted, although I have confirmed that `.jpg` is OK.

It would be good to be able to also support `.png`, but I would mark this as low severity.

This case is now closed.

Thank you.

Peace,
Mike
