### ISSUE TITLE
Command to give read/write permissions, without changing the owner of the directory?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#44]
Hi Zent,
I am now in Step 4.(3) of ["Installing Product Management Feature" Wiki](https://github.com/usbong/UsbongStore/wiki/Installing-Product-Management-Feature).

Would you know the command to give read/write permissions to an owner, without changing the owner of a directory?

It seems that I have to change the owner of the directory by using the following command to give read/write permissions.

`sudo chown username: directory`

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi MIke,

Assuming you are inside the directory you want to update, please try:

sudo chmod o+rw .

Notes:
(1) sudo: do action as root

(2) chmod: change permission

(3) o: owner

(4) +: give

(5) rw: read and write

(6) '.' - the folder I am in right now

In human terms: "Using root, give the folder I am in right now read and
write access for the user who created it."

Have a good day ahead!

**Comment by zent-lim** [comment]
Wait

**Comment by zent-lim** [comment]
The correct command is:

sudo chmod u+rw .

"o" is others

"u" is user (user who created directory)

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

It seems that if we want
to maintain a tight security,
the best course of action
is to put the owner in a group,
and then have that group gain
read/write permissions.

This is because it appears
that we cannot use `chmod`
to give read/write permissions
to a specific user.

Please never hesitate to correct me 
if my understanding is wrong.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Please read on.

On Sun, Jan 7, 2018 at 3:30 PM, Masarap Mabuhay <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the replies.
>
> It seems that if we want
> to maintain a tight security,
> the best course of action
> is to put the owner in a group,
> and then have that group gain
> read/write permissions.
>
This course sounds secure to me.

This way both your apache user and your ssh user can have write access to
the files.

> This is because it appears
> that we cannot use chmod
> to give read/write permissions
> to a specific user.
>
Yes.

Using chmod user settings, at best you can only give it the the creator of
the file.

So if you want more than one user to have write access, you change the
group settings instead.

> Please never hesitate to correct me
> if my understanding is wrong.
>
Have a good Sunday ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the response.

Agreed. This case is now closed.

Thank you.

Peace,
Mike
