### ISSUE TITLE
Auto-email Template 2:  hich Usbong Store Auto-email SQL file should be pre-installed?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#46]
Hi Zent,
I am now reviewing your [Installing Auto Email Template 2 wiki](https://github.com/usbong/UsbongStore/wiki/Installing-Auto-Email-Template-2).

In "Step2: Import New SQL", may I ask which Usbong Store Auto-email SQL file should be pre-installed, before importing the SQL in (1)?

(1) https://github.com/usbong/UsbongStore/blob/master/auto-email/usbong_store_auto_email_v07_to_v08.sql

If I've already imported [usbong_store_auto_email_v08.sql](https://github.com/usbong/UsbongStore/blob/master/auto-email/usbong_store_auto_email_v08.sql), would I still need to import the aforementioned SQL commands?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) Importing usbong_store_auto_email_v07_to_v08.sql requires that you are
at least using usbong_store_auto_email_v07.sql

(2) If you have imported usbong_store_auto_email_v08.sql, then there is no
need to use usbong_store_auto_email_v07_to_v08.sql

IMPORTANT

*In live server, please use the patch
usbong_store_auto_email_v07_to_v08.sql instead of
usbong_store_auto_email_v08.sql*

Using usbong_store_auto_email_v08.sql requires you delete existing tables
first.

It's not something you'd like to do in live server.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

When you say, "Using usbong_store_auto_email_v08.sql requires you [to] delete existing tables
first.", did you mean that it will only delete all `auto-email` tables?

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

The sql file itself will not delete tables.

But new tables columns in v8 will not be reflected on install properly.

For it to reflect properly, admin will need to delete auto email tables
manually.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the clarification.

OK! Yes, I meant that if I use `usbong_store_auto_email_v08.sql`, I'd have to delete all auto-email tables.

And if there's existing data in the auto-email tables, I'd better use `usbong_store_auto_email_v07_to_v08.sql`.

But if I'm OK with deleting all auto-email tables, I can simply go ahead with using `usbong_store_auto_email_v08.sql`.

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Yes...

Yes...

Also Yes.

Happy weekend! 😀

P.S.
Please be reminded that auto-email module is now dependent on a new
database field stored in product table.

The field is product.external_url.

I think you already installed this in your system, but just in case, the
sql is in:
https://github.com/usbong/UsbongStore/blob/master/auto-email/product_table_add_external_url_and_show_v01.sql

**Comment by masarapmabuhay** [comment]
OK! Thank you!

Peace,
Mike
