### ISSUE TITLE
Auto-email: email_frame_single_template, instead of image box, text area?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#47]
Hi Zent,
I am experiencing this peculiar behavior on prod.

As I was creating a new auto-email to send using the new `email_frame_single_template`, instead of an image box, a text area is shown.

When I click the "Choose File"/"Browse..." button, however, the file name of the image I selected is shown.

I've used both Chrome and Firefox to verify this.

Google Chrome: Version 63.0.3239.132 (Official Build) (64-bit)
Firefox Quantum: 57.0.2 (64-bit) 

Interestingly, this does not occur in my Ubuntu on VirtualBox.

Would you know what could be the probable cause?

Perhaps, there is something that I have not yet installed or configured?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Please check if you have the folder and its contents in the server being
used:

UsbongStore/usbong_store/assets/js/cropit/

If that's not the problem, let's investigate further.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Your advice resolved the issue.

Thank you.

Peace,
Mike
