### ISSUE TITLE
Auto-email: Edit email results to "404 Page Not Found" Error

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#48]
Hi Zent,
I encountered the following error when I attempted to edit my auto-email email from the auto-email admin page.

> 404 Page Not Found Error

Perhaps, one of your updates caused this portion of auto-email to break?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) Pls check config/routes.php in the server being tested.

Pls check if it has the entries below:

$route['auto-email/edit/template/(:num)/(:any)']   =
'auto-email/administer/edit/template/$1/$2';
$route['auto-email/edit/data/(:num)']              =
'auto-email/administer/edit/data/$1';
$route['auto-email/edit/products/(:num)/(:any)']   =
'auto-email/administer/edit/products/$1/$2';
$route['auto-email/edit/products/(:num)']          =
'auto-email/administer/edit/products/$1';
$route['auto-email/edit/save/(:num)'] = xxx


(2) if this doesn t resolve it, pls send me exact url used.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the response.

Except for the the following final entry, your suggestion resolved the issue.

`$route['auto-email/edit/save/(:num)'] = 'auto-email/administer/edit/save/$1';
`

Thank you.

Peace,
Mike
