### ISSUE TITLE
Auto-email: email_frame_single_template, increase font size of the message portion

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#50]
Hi Zent,
Would you agree to increase the font size of the message portion to make it easier to read?

We can pattern it with the "Call to Action Text", whose font size appears to be at least 14pt.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Ok!

I ll do this early next week. Currently, i have no access to laptop.
(Replying via mobile)

Morning!

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
<Added Mike's Personal Email for Image Attachment>

Good Day Mike!

I resolved this in the commits below:

(1) commit 6687710ff5e8478eacc64c4c172c3175b10d6434

Date:   Sun Jan 14 20:11:41 2018 +0800

Note: Resolved issue 50.

(2) commit 85aacfb0eef8119114b6051d92069188223874d1

Date:   Sun Jan 14 20:18:01 2018 +0800

Note: Updated preview image of email_frame_single_template.jpg.

Shown is a sample:


​

Have a good evening ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. The font size of the preview image appears correct.

However, when the auto-email email is actually sent, the font size is not the same as the one in the preview image.

I have verified this on gmail, while using the Chrome web browser.

Version 63.0.3239.132 (Official Build) (64-bit)

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
(Added Mike s personal email)

Hi Mike,

(1) Pls see attached file for what the font looks like on my end.

It looks correct.

(2) pls send me a copy of the email u gegenerated.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

1) OK. 
--> May I ask if you are also able to successfully attach the image file in your message here on GitHub? 
--> If yes, it should make it easier for people to understand how we resolved this issue.

2) I have forwarded you the email that auto-email generated.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Unfortunately, the msg can t be seen in git hub:
https://github.com/usbong/UsbongStore/issues/50

I have replied nxt steps to ur email.

Moring!

**Comment by zent-lim** [comment]
Here was my  msg to ur email:

Hi Mike

Tnx for the email.

(1) Kindly check if the diff in the url below made it to server being tested:
https://github.com/zent-lim/UsbongStore/commit/6687710ff5e8478eacc64c4c172c3175b10d6434

(2) pls delete old email from ur inbox and resend to ur inbox again.

Tnx! Morning!

P.s.
Forgot to send a pull request. Sending it now.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK. I've verified that the font of the email I sent using auto-email is now larger.

Your pull request resolved the issue.

Thank you.

Peace,
Mike
p.s. let's also attach the image files in our GitHub correspondence from hereon.

**Comment by zent-lim** [comment]
Hi Mike,

Okly dokly.

It seems like github cant render images.
(1) when i attach an image file, it doesn t show
(2) when i attach an inline image, it also doesn t show

If otherwise pls inform.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. Do you encounter this same behavior on desktop, not only on mobile?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Yep.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

It could be a web browser issue.

In my case, I am able to successfully attach an image here on GitHub on my desktop, using Chrome.

Having said this, I would suggest that you contact GitHub regarding help with this issue.
https://github.com/contact

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I see.

I use firefox by default.

I ll try chrome on the next case then.

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
OK, Zent!

Peace,
Mike
