### ISSUE TITLE
Auto-email: email_frame_single_template, new email pre-loads data from previous email 

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#51]
Hi Zent,
I've observed that when I create a new email using auto-email's `email_frame_single_template`, it loads data from the previous email.

Shouldn't the new email not pre-load any data?

Please correct me if my understanding is wrong.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

It should give u a blank slate.

Ill check on monday.

Good afternoon!

**Comment by zent-lim** [comment]
<Added Mike's Personal Email for Image Attachement>

Hi Mike,

I did the following:

(1) Create new email in the url below:
https://store.usbong.ph/index.php/auto-email/create/template/1

(2) After creating the first email, I created another email using the same
url:
https://store.usbong.ph/index.php/auto-email/create/template/1

The form showed a clean slate as shown below:


​
CODE VERSION

commit 4261348266d9204324001eca4b5ff067ed0e71e2

Date:   Mon Jan 8 13:22:34 2018 +0800

Note: Added auto-email template 2. Overhauled auto-email administer to
allow image data type and allow use of template 2.

REQUEST

Could you tell me how to recreate the problem?

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK. Here are the steps:
1) Select an existing auto-email email and click the "Edit Email" button.
2) Return to the auto-email admin page by clicking the "Auto Email" link.
3) Click the "+ Create New Email" button.
4) Click "Set Data".

The following fields would already have pre-loaded data:
1) "Email Subject"
2) "Message"
3) "Call to Action Text"
4) "Call to Action URL" 

Please never hesitate to let me know if there's anything else that you need.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Ok! I ll retry this scenario this evening.

Morning!

**Comment by zent-lim** [comment]
Hi Mike,

I was able to re0create the problem using the transitions you itemized.

I'll analyze the problem further.

**Comment by zent-lim** [comment]
Hi Mike,

(1) I resolved this in the commit below:

commit 7d6fba8065dc85b4e75aeb3a5b720d4ddc31e15a

Date:   Mon Jan 15 19:10:03 2018 +0800

Note: Resolved issue 51.

(2) I submitted a pull request as well:

https://github.com/usbong/UsbongStore/pull/53

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK. I have merged your pull request.
I have also verified that your update has indeed resolved this issue.

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
You're welcome! 😀
