### ISSUE TITLE
Product Management: "undefined function create_jpg_file_name()" error

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#54]
Hi Zent,
I encountered the following error while using Usbong Store's Product Management feature.

```
An uncaught Exception was encountered
Type: Error

Message: Call to undefined function create_jpg_file_name()

Filename: /var/www/html/application/models/Product_Model.php

Line Number: 138

Backtrace:

File: /var/www/html/application/controllers/Manage.php
Line: 127
Function: insertRow

File: /var/www/html/application/controllers/Manage.php
Line: 202
Function: render_product_form

File: /var/www/html/index.php
Line: 308
Function: require_once
```

I have updated to the newest versions based on our GitHub repository the Model, View, and Controller folders on prod.

It is possible that I may have to also update a configuration file.

Would you be able to help me identify that particular file?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike!

Pls check if the said function in the file below made it to the server
being tested:
https://github.com/usbong/UsbongStore/blob/master/usbong_store/application/helpers/MY_url_helper.php

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the response.

Your advice resolved the issue.

This case is now closed.

Thank you.

Peace,
Mike
