### ISSUE TITLE
Product Management: "Language" field should be textfield, instead of dropdown

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#55]
Hi Zent,
I noticed that while adding a new product using the Product Management feature, the `Language` field is `dropdown`, instead of a `textfield`.

I am OK with using `dropdown`, but there should be a way to immediately put an option that is not included in the `dropdown` list.

It may be simpler to just use a `textfield`, and then add an example answer as a form of hint. 

It can be similar to the following, although it need not necessarily animate.
https://store.usbong.ph/sell/

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Okly dokly Mike,

I ll change it to a text field this evening.

Morning!

**Comment by zent-lim** [comment]
Hi Mike,

(1) I resolved this in:

commit d28100012c5f1728229af96c138ac4ac55d3f11c

Date:   Wed Jan 17 10:31:54 2018 +0800

Note: Resolved issue 55.

(2) I sent a pull request in:

https://github.com/usbong/UsbongStore/pull/56

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

I have verified on prod that your pull request resolved the issue.

This case is now closed.

Peace,
Mike
