### ISSUE TITLE
Auto-email: warning message/hint that says present data will be deleted when changing to a different template

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#59]
Hi Zent,
This is in response to issue: [Auto-email: email_frame_simple_template, does not load the data of the existing auto-email](https://github.com/usbong/UsbongStore/issues/58#event-1427623030).

Would it be possible to provide the admin person a warning message or a hint that says that the present data will be deleted if he/she changes to a different template?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Sure. I'll add it this evening.

Morning!

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) I resolved this in:

commit 242e38003d2cdd9c270e271eb1c3f16c5b0828e6

Date:   Thu Jan 18 19:54:59 2018 +0800

Note: Resolved issues 59 and 60.

(2) I submitted a pull request in:

https://github.com/usbong/UsbongStore/pull/61

(3) The warning message will show when mouse is hovered over the checkbox.

![warning](https://user-images.githubusercontent.com/8021327/35097153-f3dc9868-fc89-11e7-816c-f8afde13f220.png)

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have updated the code on prod based on your newest commit.
However, the warning message doesn't appear when I hover my mouse over the checkbox.

Could this update of yours have been affected by your other update (https://github.com/usbong/UsbongStore/issues/60#event-1429481992)?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike!

The update below shows a diff:
https://github.com/zent-lim/UsbongStore/commit/242e38003d2cdd9c270e271eb1c3f16c5b0828e6

Pls check if the update in file below made it to server being tested:
usbong_store/application/views/auto-email/create_template.php

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! Yes, I ended up uploading onto prod an older version of the code.

Your advice helped me resolve the issue.

This case is now closed.

Thank you.

Peace,
Mike
