### ISSUE TITLE
Are you using any 3rd party software, e.g. SourceTree, to pull/push to our GitHub repo?

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#6]
Hi @zent-lim,
May I ask if you're using any 3rd party software, e.g. SourceTree, to pull/push to our GitHub repo?

Thank you!

Peace,
Mike
p.s. I've just installed (Ubuntu 16.04.3 LTS) on VirtualBox and am now going through your guide.

**Comment by zent-lim** [comment]
Afternoon Mike!

Nope. Just good old git hub with unix command line.

Have a good day ahead!

P.s.
I received another invite for one of ur repos. I ll accept when i get
access to my laptop. 😊

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply!

OK! Got it!

Peace,
Mike
