### ISSUE TITLE
Auto-email: from "Edit Email" button, go to "Set Data" page, instead of "Choose Template" page

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#60]
Hi Zent,
Would you be able to redirect the link, such that when the admin person clicks the "Edit Email" button, it directly transfers him/her to the "Set Data" page, instead of the "Choose Template" page?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Sure. I'll do that this evening as well.

Edit feature will no longer allow template changes.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK!

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) I resolved this in:

commit 242e38003d2cdd9c270e271eb1c3f16c5b0828e6

Date:   Thu Jan 18 19:54:59 2018 +0800

Note: Resolved issues 59 and 60.

(2) I submitted a pull request in:

https://github.com/usbong/UsbongStore/pull/61

(3) Edit feature will no longer allow changing of template. Please see header below. "Choose Template" is no longer available.

![nochoosetemplate](https://user-images.githubusercontent.com/8021327/35097278-69c46146-fc8a-11e7-8afa-8fe8cab52a85.png)

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Upon verifying this update on prod, it seems that the "Edit Email" button has now disappeared from the Auto-email admin page.

Please kindly inform me if my observation is the same as what you have on your local machine.

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! Yes, I ended up uploading onto prod an older version of the code.

Your advice helped me resolve the issue.

This case is now closed.

Thank you.

Peace,
Mike
