### ISSUE TITLE
Product Management: Zoom In/Out Icons = Misplaced

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#68]
Hi Zent,
I hope you are doing well.

I was using the Product Management feature of the Usbong Store, and I noticed that the Zoom In icon should be where the Zoom Out icon is, and vice-versa.

Could you verify if this is the same with your local version of the Usbong Store?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Sorry bout that.

I fixed it.

You should get the resolved version when you accept the latest unmerged
pull request:
https://github.com/usbong/UsbongStore/pull/67

Afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Your fix resolved the issue.

This case is now closed.

Thank you.

Peace,
Mike
