### ISSUE TITLE
Forgot Password Feature: After clicking reset password link, automatically show the Update Password page

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#70]
Hi Zent,
I hope you are doing well.

I am now performing Unit Testing of the Forgot Password Feature.

Would you agree to immediately show the Update Password page after the customer clicks the reset password link in the email?

https://store.usbong.ph/account/updatepassword/

This may be better than having the customer sign-in using the new password, and then going to the Update Password page.

We can also already have the Usbong Store server automatically put the new password in the Current Password field.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

The page you mentioned requires the user to be signed in for access.

If we're going to use the reset password script to sign the user in, there's going to be negative user experience associated with this:

(1) users dont like it when scripts sign in for them (it reminds them of the feeling that our admin can access their data anytime)

(2) Session data disappears. Here's a theoretical example.

Supposed the user has some session data stored using the guest account (cart for example). This data disappears with the script sign in.

Are you sure you'd like to do proceed this way?

Thanks!

**Comment by zent-lim** [comment]
Evening Mike!

When things are not so busy on your end tomorrow, please get back to me on this issue.

Thanks!

**Comment by zent-lim** [comment]
Hi Mike,

I resolved this in:

(1) commit 554e92f5ff083d4a563b063f300a3ad242c391a4

Author: zent <zentlim@gmail.com>
Date:   Thu Mar 22 19:26:52 2018 +0800
Note: Resolved issues 65 and 70.

(2) Pull req: https://github.com/usbong/UsbongStore/pull/79

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the update.

OK! I have merged your pull request with our official Usbong Store repository here on GitHub.

I have also verified that your update has resolve this issue.

Thank you.

Peace,
Mike
