### ISSUE TITLE
Auto-email: Welcome message doesn't appear in the email body

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#76]
Hi Zent,
I was using auto-email, and I noticed that the welcome message text doesn't appear in the email body.

It seems to be set to the default message, which is "The Usbong Store has new recommendations for you."

Shouldn't the welcome message appear above the default message?

Please correct me if my understanding is wrong.

Thank you.

Peace,
Mike
p.s. I should mention that I was using "email_frame_simple_template".

**Comment by zent-lim** [comment]
Hi Mike,

U removed it in one of ur past code commits.

I think u did it intentionally.

Good afternoon!

**Comment by zent-lim** [comment]
Hi Mike,

You commented it out in this commit on Oct 2017:

Url:
https://github.com/usbong/UsbongStore/commit/d305a34f42146e2791e36d1fed116187081d7dd7#diff-a5ea4528b6cebdd1ac8acc8ef362c1c5

In comment you said:
+updated: design layout of email from auto-email for product item rec…

So I assumed you wanted it removed on purpose.

Good afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. I have uncommented it out.
I have also increased its font size.

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Okly dokly! :)
