### ISSUE TITLE
Auto-email: in email_frame_simple_template, welcome message field should have more space/rows

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#77]
Hi Zent,
I hope you are doing well.

It seems to me that the welcome message field in auto-email's email_frame_simple_template should have more space/rows, to mimic somewhat writing an email message.

Please tell me if you agree with me on this.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
MornIng Mike!

Let me look at it early this coning week.

Have a good day ahead! 😊

**Comment by zent-lim** [comment]
Hi Mike,

It looks good on my end. (Please see image.)

![screenshot_20180312-132024](https://user-images.githubusercontent.com/8021327/37266952-855743d2-25f8-11e8-8068-19dc3956d9a5.jpg)

REQUEST

Could you show me a sample from your end?

Maybe I'm not seeing something with my test send.

Thanks lots!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Did you verify this in the **Create Email Subject and Welcome Message** page?
https://store.usbong.ph/auto-email/create/data

Here is a screenshot:

![image](https://user-images.githubusercontent.com/344066/37268133-5fa7c844-25ff-11e8-88dc-4fb4c1247ebb.png)

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Ah.. i see... i see...

(1) I misunderstood.

     I thought you were talking about line height and font size on the
email side.

(2) Thanks for clarifying.

     Html input element was intentionally used for this form element cause
the welcome messages are typically short simple one sentences.

     This was done by design so users can focus on the product list instead
of the welcome message.

Should you prefer textarea over input, simply do the ff on database side:

(1) Table: auto_email_template

(2) Row: 1 (email_frame_simple_template)

(3) Column: data_01_type

Change column data from "text" to "textarea".

Have a good day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have verified 
your recommendation
on the DB side.

`email_frame_simple_template`'s 
`data_01_type` field is already
set to `textarea`.

May I kindly ask what would be
your alternative recommendation
to address this issue?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Pls check that the database you are using matches the server being tested.

If it does, let s check your source code next.

Afternoon!


On Mar 12, 2018 3:18 PM, "Masarap Mabuhay" <notifications@github.com> wrote:

Hi Zent,
Thank you for the reply.

I have verified
your recommendation
on the DB side.

email_frame_simple_template's
data_01_type field is already
set to textarea.

May I kindly ask what would be
your alternative recommendation
to address this issue?

Thank you.

Peace,
Mike

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/usbong/UsbongStore/issues/77#issuecomment-372213614>,
or mute the thread

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK. The DB I used from one of my local servers
to verify your recommendation wasn't updated.

I can confirm now, however, 
that your recommendation did, 
in fact, resolve this issue.

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Awesome! 😁😁😁

Usbong stuff for the week closed! I ll do what i can to speed up estimate
on phase 5. 😁😁😁

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike
