### ISSUE TITLE
Product Management: Unable to upload different images with the same filenames

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#78]
Hi Zent,
I hope you are doing well.

When I upload images with the exact, same filenames, even if the content of the images are different, the Product Management feature/tool is unable to successfully store the files on the prod server.

May I kindly ask you if this behavior also occurs in your local server?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I think we ran this scenario before and i could not recreate.

We then ran tests and concluded it was ur file permissions.

If not, pls clear browser cache.

Tnx!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, we had a similar issue before.

In this case, though, I was uploading **several product items with the same image filenames**.

If I rename the image filenames, I am able to successfully upload the files.

Please do let me know what would be your recommended way to resolve this issue.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) Pls do an ls -la for the entire image directory

(2) pls identify the problem filename for me.

Thanks! Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

It seems that I can no longer replicate the issue.

This may be due to my updating the file/folder permissions as you advised earlier.

I will let you know if this issue occurs again.

In the meantime, this issue is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Awesome! 😁
