### ISSUE TITLE
Auto-email: "404 Page Not Found" when "Open Draft Email" button is clicked

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#82]
Hi Zent,
I hope you are doing well.

I was verifying your auto-email update, and I noticed that when I click the "Open Draft Email" button, I get a "404 Page Not Found" error.

Here are the steps I did:
1) In Auto-email (Admin) page, click "+Create New Email".
2) Select "email_frame_simple_template".
3) Enter "Hey there!" in the Email Subject.
4) Click "SAVE".
5) Click "Auto email" to return to the Auto-email (Admin) page.
6) Click "Open Draft Email".

My Model-View-Controller folders are up-to-date with our GitHub repository here.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Pls check that your routes file is updated.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I've updated the routes.php file as you advised.

This issue is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Happy sunday! 😊

**Comment by masarapmabuhay** [comment]
Thank you, Zent! 

Peace,
Mike
