### ISSUE TITLE
Merchant Management: link and/or web address to access the page

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#86]
Hi Zent,
I hope you are doing well.

May I kindly ask where I may be able to access the Merchant Management page?
Would you be able to send me the link and/or web address?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Details are in:
(1) Subject: Usbong Store CMS Phase 1: Auto Email Enhancement, Product
Management Enhancement, Account Enhancement, Merchant Management
(2) Date: Mar 24, 2018

Depending on how your environment is set up, it will likely be in eith of
the ff:
(1) https://store.usbong.ph/index.php/manage/merchants
(2) https://store.usbong.ph/manage/merchants

Good afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Yes, given the links you provided, I am able to access the Merchant Management page.

This case is now closed.

Thank you.

Peace,
Mike
