### ISSUE TITLE
When email is sent using auto-email, the images are not included.

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#9]
Hi Zent,
I was able to successfully send an email using auto-email!

The issue now though is that the email does not properly display the images, e.g. product images.

What could be the cause?

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Evening Mike!

===================
Most probable cause:
===================

(1) Gmail can only fetch from your live server. It can't do http request to
your local environment.

(2) In which case, please set the ff in your local env to use live server
settings:
File: application/config/config.php
Default Param: $config['base_url'] = 'http://localhost:8080/usbong_store/';
New Param: $config['base_url'] = 'https://store.usbong.ph/';

===================
If That's Not The Problem:
===================

Could you do the following for me please?

kick an email to zentlim@gmail.com using your environment please

If you are using your live server:
(1) Add my contact details to customer table.

(2) Set auto_email_schedule.start_id and auto_email_schedule.end_id to my
customer_id

If you are using a local environment:
(1) Set customer_id = 1 email's to zentlim@gmail.com

(2) kick a broadcast

Thanks lots!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Your hypothesis is correct.

Setting the following resolved the problem:
$config['base_url'] = 'https://store.usbong.ph/';

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
U re welcome! 😁😁😁
