### ISSUE TITLE
Mobile Responsiveness: when the browser is in full screen, there are unaligned page components

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#90]
Hi Zent,
I hope you are doing well.

After doing Unit-Testing of your mobile responsiveness pull request, I found that when the browser is in full screen, the components of the page are not properly aligned.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/344066/39393301-32195660-4af6-11e8-9a66-841d7aca58b9.png)

Observations:
1) The Usbong Store icon, the search box, the login link, and the shopping cart icon are no longer in only one row.

2) The categories, or product types, are also not in only one row.

3) The product item images have also become larger.

What could be the probable cause?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Morning Mike!

Pls run the ff commands in ur test server:

(1) git log -5

(2) git status

Then after you send me the results, i ll ask you to do git diff on specific
files.

Thanks!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

The present local server that I'm using is running on Windows.

After downloading the newest version from GitHub using SourceTree, I copy-pasted the files that you changed based on the following:
https://github.com/usbong/UsbongStore/pull/89/files

Can you confirm that when in full screen, the issue I reported doesn't occur in your local server?

I used the following:

`Google Chrome: Version 65.0.3325.181 (Official Build) (64-bit)`

Interestingly, this is what I see when in full screen, using Firefox Quantum (58.0.2 (64-bit)).

![image](https://user-images.githubusercontent.com/344066/39426389-2abdeb8e-4cb2-11e8-93b9-88c39ff8c29e.png)

The following observation I reported appears to have been resolved, although there's a margin to the left and right.
1) The Usbong Store icon, the search box, the login link, and the shopping cart icon are no longer in only one row.

From this, the issue seems to be browser-related, among others.

Thank you.

Peace,
Mike
p.s. I also have a local server that's running Ubuntu using Virtual Box. I can update that to the newest version using our Usbong Store repository here on GitHub. Please tell me if this won't be necessary.

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Good Day Mike,

(1) I resolved this in:

    commit 494ce084451f6858a72d74f15154ea68924c298d
    Author: Zent Lim <zentlim@gmail.com>
    Date:   Tue May 1 19:42:42 2018 +0800
    Note: Resolved issue 90.

(2) I sent pull request in:

    https://github.com/usbong/UsbongStore/pull/91

(3) Please check.

![chrome](https://user-images.githubusercontent.com/8021327/39471878-4d628386-4d78-11e8-8d27-3c4e0fc7c6a4.png)

Evening!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have merged your pull request with the master branch.

I was also able to resolve the following observation I reported earlier:

2. The categories, or product types, are also not in only one row.

Using `container-fluid`, instead of `container`, appears to be the correct way to resolve it.

<br>

Moreover, I've updated the login row:
1) I removed the added padding/margin space to the left and right.
2) I increased the search box length.

I've committed these code updates here: https://github.com/usbong/UsbongStore/commit/caa30b3d5ad0a2184f04c1d9a1c7d6113da3d4d3

Here are screenshots:
1) Google Chrome: Version 65.0.3325.181 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/344066/39555873-e66e0d3e-4eae-11e8-9884-132cb337f172.png)

2) Firefox Quantum (58.0.2 (64-bit))

![image](https://user-images.githubusercontent.com/344066/39555886-ffbd0a88-4eae-11e8-9a14-b62977897730.png)


Having said these, observation 3. is still unresolved.

3. The product item images have also become larger.

Would you be able to figure out how to resolve it?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

On Thu, May 3, 2018 at 8:59 AM, Masarap Mabuhay <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> I have merged your pull request with the master branch.
>
> I was also able to resolve the following observation I reported earlier:
>
>    1. The categories, or product types, are also not in only one row.
>
> Using container-fluid, instead of container, appears to be the correct
> way to resolve it.
>
Ok!

I recommend still using container instead of container-fluid.
(1) Basically I tested both, and when you start adding more categories, it
really wont fit in one row.
(2) But if you're happy with how it looks, then that's good.


>
> Moreover, I've updated the login row:
>
>    1. I removed the added padding/margin space to the left and right.
>
> The padding was intentional.
(a) If you remove it, the alignment of header vs footer becomes misaligned.
When the user looks at the whole page, it will feel a bit off.
(b) If you remove it, it will look bad particularly on xs.

But if you've tested and it works, then no problem.

>
>    1. I increased the search box length.
>
> The shortened length was intentional. If you increase it, the layout will
be damaged on xs.

But if you've tested and it works, then no problem.

>
>
> I've committed these code updates here: caa30b3
> <https://github.com/usbong/UsbongStore/commit/caa30b3d5ad0a2184f04c1d9a1c7d6113da3d4d3>
>
> Here are screenshots:
>
>    1. Google Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
>
> [image: image]
> <https://user-images.githubusercontent.com/344066/39555873-e66e0d3e-4eae-11e8-9884-132cb337f172.png>
>
>    1. Firefox Quantum (58.0.2 (64-bit))
>
> [image: image]
> <https://user-images.githubusercontent.com/344066/39555886-ffbd0a88-4eae-11e8-9a14-b62977897730.png>
>
> Having said these, observation 3. is still unresolved.
>
>    1. The product item images have also become larger.
>
> Would you be able to figure out how to resolve it?
>
Making the images bigger is also intentional.

It gets the attention of your audience better than smaller images.

Are you sure you want them to be smaller? If yes, please inform me how many
images you'd like to have per row. It must be divisible by 12.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! I'll take note of your response to my updates.

Regarding smaller images, yes, it appears better 
if the image size allows for 5 product images per row, 
which is what we already do on prod.

Moreover, yes, indeed, the sum of the column indices must be 12. 

However, we do not necessarily have to use exactly up to 12; 
If we use only 10 (from 5 * 2), it would still be OK.

Thank you.

Peace,
Mike
p.s. please also take into account the Merchant page, e.g. https://store.usbong.ph/b/Books/1. Although it also uses 5 product item images per row, the images are smaller due to the left panel being used by the Merchant and his/her categories/product types.

**Comment by zent-lim** [comment]
Hi Mike,

On Fri, May 4, 2018, 8:28 AM Masarap Mabuhay, <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> OK! I'll take note of your response to my updates.
>
> Regarding smaller images, yes, it appears better
> if the image size allows for 5 product images per row,
> which is what we already do on prod.
>
> Moreover, yes, indeed, the sum of the column indices must be 12.
>
> However, we do not necessarily have to use exactly up to 12;
> If we use only 10 (from 5 * 2), it would still be OK.
>
I ll send you an update.

I have a feeling though that:
(1) the gutter left might look bad
(2) the more complex logic may damage smaller screen

I ll test carefully before i push the code.

> Thank you.
>
> Peace,
> Mike
> p.s. please also take into account the Merchant page, e.g.
> https://store.usbong.ph/b/Books/1. Although it also uses 5 product item
> images per row, the images are smaller due to the left panel being used by
> the Merchant and his/her categories/product types.
>
Do you have an action item for this mode?

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK!

Peace,
Mike
p.s. We may have to add taking into account the Merchant page, as an action item in the next project phase.

**Comment by zent-lim** [comment]
Hi Mike,

Please see sample below for a five column product list.

As I have anticipated:

(1) The gutter created looks awkward.

![screenshot-2018-5-5 usbong store](https://user-images.githubusercontent.com/8021327/39659859-b67c18e8-5064-11e8-8429-13f269ba9585.png)

(2) It breaks on some screen size. In this test case, it breaks on sm screen.

![screenshot-2018-5-5 usbong store](https://user-images.githubusercontent.com/8021327/39659862-ce4b298c-5064-11e8-9e0a-ce1589c56d44.jpg)

RECOMMENDATION

(1) I recommend the status quo i sent at commit f6e10ff4b6b09ab18626e3de824873e2c632d345.

      It uses 4 per row for bigger more engaging images for your customer.

(2) Alternatively, you can try 6 per row. (4 is still my best choice.)

![screenshot-2018-5-5 usbong store 1](https://user-images.githubusercontent.com/8021327/39659877-3f2ad666-5065-11e8-83cb-a8db1df15e32.png)

(3) Alternatively, we can push my local draft. (Again, I will have to say this is a worse design direction.)

QUESTION

Which option would you like to do?

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the update.

Can you send me first a pull request,
so I can verify your code?

In prod, we are able to use 5 auto-rescaled 
product item images per row 
without the extra margin to the right.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

(1) It's a bad idea to push code that is unstable. It will eat more time for both of us revising code later.

      This code is not stable for the reasons stated above.

(2) In the old version, you were able to do a five column catalogue because it was not mobile responsive. Meaning, it did not matter if md to xs layout was damaged.

(3) In this version, we want xs to md to render properly.

(4) A five col list is possible, but:

     (a) the implementation will be a bit different which will require more time and resources

     (b) the images will be less engaging which might be backwards for customers (this is subjective of course)

QUESTION

To make the code more stable, how about I push code for a 6 col product catalogue?

(1) Unlike a five col catalogue, this 6 col catalogue will maintain correct layout from xs to lg.

(2) That will also decrease the image size as you prefer (although I recommend against)

But the bottom line is, the code will be a stable base. Meaning, it will be good foundation for you to run your experiments over to try and make it a five fol catalogue.

Does that work for you?

**Comment by zent-lim** [comment]
Hi Mike,

Does my recommendation work for you?

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK! Please send me the pull request.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Okly dokly!

Let me just clean things a little bit and do some more compatibility tests.

I'll push a 6 col catalogue within the hour.

Morning!

**Comment by zent-lim** [comment]
Hi Mike,

I submitted pull request for 6 col catalog (LG):
https://github.com/usbong/UsbongStore/pull/95

MODE - No Merchant
![screenshot-2018-5-8 usbong store 1](https://user-images.githubusercontent.com/8021327/39735438-2a57fb74-52ae-11e8-82d5-96367375eadc.png)

Mode - Has Merchant
![screenshot-2018-5-8 usbong store](https://user-images.githubusercontent.com/8021327/39735447-33b35074-52ae-11e8-9f36-44509c48c6c5.png)

Have a productive day ahead!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

OK! I have merged your pull request.
Let me verify your code update.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Okly dokly.

Catch up with you soon.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have verified your code update.

I have also made modifications 
upon System-Integration Testing.

Please update your code to my newest code commit (May 10, 2018):
https://github.com/usbong/UsbongStore/commits/master

This case is now closed.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Thank you for verifying Mike.

I have no open tickets left.

I'll wait for further feedback.

Have a good day ahead!
