### ISSUE TITLE
Unnecessary Horizontal Scroll on Beverage Pgae XS to SM

### ISSUE THREAD

**Issue by zent-lim** [usbong/UsbongStore#96]
Hi Mike,

In the latest commit below, there is new damage on xs to sm screen for beverage page.

commit d4b3d59a971b589f1d3eccad574b1ba9b27f6e57

Author: Michael Syson <masarapmabuhay@gmail.com>

Date:   Thu May 10 09:16:28 2018 +0800

Note: updated: in the Merchant page, the category/product type header, e.g. Beverages, should be on the top-left of the space provided for the main content of the page, similar to the product item page
 
There is unnecessary horizontal scroll. When you reach xs size, you'll be able to scroll to the right showing blank space.

(1) Full Screen Shot
![screenshot-2018-5-10 usbong store](https://user-images.githubusercontent.com/8021327/39848409-6283e6ac-5439-11e8-9957-3374ca820375.png)

(2) Zoom Screen Shot
![screenshot-2018-5-10 usbong store 1](https://user-images.githubusercontent.com/8021327/39848449-9aac396c-5439-11e8-9184-23fa5d2412d8.png)

I remember already having resolved this in my earlier code push as well.

commit ba60676e7b057ce9a0303aef7f2d881e33d3888d

Author: Zent Lim <zentlim@gmail.com>

Date:   Sun Apr 22 21:08:08 2018 +0800

Note: Fixed mobile responsiveness of b/beverages.

Kindly fix the issue again.

Thank you.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for reporting this issue.

Let me see what I can do.

In the meantime, I've marked this as "severity-low".

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

BACKGROUND:

I recommend this be resolved before we scale mobile responsiveness to other pages.

RECOMMENDATION:

Version: d191e89287f4ac1d3ecbe27b72e03e20e7407729

File: UsbongStore/usbong_store/application/views/templates/header_v2.php

Orig Code:

`<div class="container-fluid Header-container">`

NEW CODE:

`<div class="container Header-container">`

NOTES:

(1) This will also resolve issue 92:

      https://github.com/usbong/UsbongStore/issues/92

(2) This will open a new issue below:

![screenshot-2018-5-19 usbong store](https://user-images.githubusercontent.com/8021327/40266571-705dd244-5b80-11e8-8339-0ce8ce1144b2.png)

      (a) This issue I have already resolved in my stable Apil 22 release by shortening the search bar.

       (b) After I pushed code, you increased the length of the search bar again.

       (c) I have not yet looked into this future issue again deeply, but most likely, you simply have to shorten the search bar again.

REQUEST

Please update the code based on my recommendation or proceed as you see fit,

Best of luck!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

Not using `container-fluid` would cause 
the categories/product types to not be 
in only 1 row when in full screen.

Having said this, in the event that we do 
add more categories/product types 
so that they'll use more than 1 row, 
even when in full screen, we can set
`container-fluid` back to `container`.

At present, let's proceed 
with continuing to use 
`container-fluid`.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

It wont.

They use separate containers:
https://github.com/usbong/UsbongStore/blob/master/usbong_store/application/views/templates/header_v2.php

Pls let me know when u have resolved the issue.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! I will notify you 
when this issue has been 
resolved either by me 
or someone else.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

I resolved this in:

(1) zent repo dc29d76d5f6257619681bf91f4cff45cf61834a9

(2) pull req url: https://github.com/usbong/UsbongStore/pull/99

Afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

OK! I have already merged your pull request.

When the mobile responsiveness setting is turned on,
the Usbong Store uses your solution.

This case is now closed.

Thank you.

Peace,
Mike
p.s. Erratum in the issue name. I understand that "Pgae" is supposed to be "Page".
