### ISSUE TITLE
Auto-email: Created email is not automatically sent

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/UsbongStore#98]
Hi Zent,
I hope you are doing well.

It seems that I am unable to automatically send an email without actually clicking the "Send Email" button in the auto-email admin page.

This is even after setting the schedule, i.e. `Target Kick Time`.

Shouldn't auto-email automatically send the email by the `Target Kick Time`, without my having to click the "Send Email" button?

Please correct me if my understanding is wrong.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

No.

Automatic was my original recommendation.

But u rejected it despite many warnings.

U did the ff instead:

(1) u refused to set up the cron script i prescribed.

(2) u preferred, requested, and had me made a kick button instead.

Afternoon!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

It is likely that you misunderstood me.

Perhaps, I opted to set aside 
for later the feature to enable 
auto-email to auto-send/kick emails 
depending on the set schedule, 
or the `Target Kick Time`.

In any case, may I kindly ask 
if you can tell me again the steps 
to setup the cron script?

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Sure.

(1) pls see image below for set up:
![screenshot_20180522-123500](https://user-images.githubusercontent.com/8021327/40342359-cc76895c-5dbc-11e8-9e2f-22d42816c11b.png)

(2) pls see wiki below for kick command in crontab:
https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature

(3) if there s anything else u need, feel free to buzz.

(4) note: you may encounter issues in writing to log file. The unix owner for cron script and kick script may have been configured differently in ur server. In which case, simply delete the existing log file so the cron script can create a new one.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

May I clarify with you first whether 
executing the following [command](https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature)
would cause Auto-email to send the email 
based on the schedule that I set?

`php index.php auto-email/autoemail run`

Or, will it immediate send it, 
in the same manner as 
the "Send Email" button?

Thank you.

Peace,
Mike

Reference: 
[1] https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature; last accessed: 20180523

**Comment by zent-lim** [comment]
Hi Mike,

On Wed, May 23, 2018 at 9:27 AM, Masarap Mabuhay <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> May I clarify with you first whether
> executing the following command
> <https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature>
> would cause Auto-email to send the email
> based on the schedule that I set?
>
> php index.php auto-email/autoemail run
>
Yes.

It will follow the schedule.

> Or, will it immediate send it,
> in the same manner as
> the "Send Email" button?
>
The "Send Email" will not send an email that is not yet in schedule.

It also follows your schedule. It will only send emails that are already
due.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

I have executed the command on prod:
`php index.php auto-email/autoemail run`

However, the email is not automatically sent,
even though its set "kick" schedule has passed.

I have also clicked the admin page's 
"Refresh Page" button, but to no avail.

When I click the "Send Email" button, 
Auto-email is able to successfully 
send the email to customers.

Thank you.

Peace,
Mike
p.s. Erratum: Or, will it **immediately** send it...

**Comment by zent-lim** [comment]
Hi Mike,

(1) It likely has to do with my message below on May 22:

"you may encounter issues in writing to log file. The unix owner for cron
script and kick script may have been configured differently in ur server.
In which case, simply delete the existing log file so the cron script can
create a new one."

(2) I have documented that you must give two kinds of user access to make
log files:

     url: https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature

     section: Logging > 3 > a, b, c

REQUEST:

(1) Did you try my recommendation from May 22?

     "simply delete the existing log file so the cron script can create a
new one."

(2) If no - please try my recommendation

(3) If yes

      (a) please show me log file created from kick so I can analyze
further:

     "UsbongStore/usbong_store/application/logs/log-YYYY-MM-DD.php"

      (b) in what directory did you use to kick the script?

      (c) what unix user did you use to kick the script?

      (d) please send me result of

           (i) cd XXX/UsbongStore/usbong_store/application/logs

           (ii) ls -la

Have a good day ahead!

**Comment by zent-lim** [comment]
Hi Mike,

Thanks for the log file.

(1) You were able to send out an email using the script on 2018-05-27 07:53
to usbong.ph@gmail.com.

       Note that time 07:53 may use your live server time zone.

<-----Log Snip----->

INFO - 2018-05-27 07:53:12 --> AutoEmail: SETTING QUEUE to ACTIVE:
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> auto_email_schedule_id = 76
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> customer_ids           = 2
to 2
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> max_send               = 20
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> protocol               =
smtp
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_host              =
smtp.gmail.com
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_user              =
usbong.ph@gmail.com
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_crypto            = ssl
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_port              = 465
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> mailpath               =
/usr/sbin/sendmail
INFO - 2018-05-27 07:53:12 --> AutoEmail: Sending email to support@usbong.ph
INFO - 2018-05-27 07:53:14 --> AutoEmail: QUEUE SET to DONE.

<-----Log Snip----->

(2) To verify:

     (a) please check support@usbong.ph's email inbox

     (b) please check usbong.ph@gmail.com's email sent folder

QUESTION:

When you kicked auto_email_schedule_id = 76 on May 27, what did you use?

(a) kick button using browser

(b) kick script using command line

TEMPORARY CONCLUSION:

Either way, the kick button and the kick script uses THE SAME core
component below:
UsbongStore/usbong_store/application/controllers/auto-email/Autoemail.php

So the core script is working.

Have a good day ahead.

**Comment by zent-lim** [comment]
<Corrected emails>

Hi Mike,

Thanks for the log file.

(1) You were able to send out an email using the script on 2018-05-27 07:53
to support@usbong.ph.

       Note that time 07:53 may use your live server time zone.

<-----Log Snip----->

INFO - 2018-05-27 07:53:12 --> AutoEmail: SETTING QUEUE to ACTIVE:
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> auto_email_schedule_id = 76
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> customer_ids           = 2
to 2
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> max_send               = 20
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> protocol               =
smtp
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_host              =
smtp.gmail.com
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_user              =
usbong.ph@gmail.com
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_crypto            = ssl
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> smtp_port              = 465
INFO - 2018-05-27 07:53:12 --> AutoEmail:  |--> mailpath               =
/usr/sbin/sendmail
INFO - 2018-05-27 07:53:12 --> AutoEmail: Sending email to support@usbong.ph
INFO - 2018-05-27 07:53:14 --> AutoEmail: QUEUE SET to DONE.

<-----Log Snip----->

(2) To verify:

     (a) check support@usbong.ph's email inbox

     (b) check usbong.ph@gmail.com's email sent folder

QUESTION:

When you kicked auto_email_schedule_id = 76 on May 27, what did you use?

(a) kick button using browser

(b) kick script using command line

TEMPORARY CONCLUSION:

(1) Either way, the kick button and the kick script uses THE SAME core
component below:
      UsbongStore/usbong_store/application/controllers/auto-
email/Autoemail.php

      The kick button calls the kick script simply with an extra input
passed.

(2) So the core script is working.

Have a good day ahead.

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies.

(1) Yes, for the email I sent on `2018-05-27 07:53`, I used the "Send Email" button.
--> `07:53` already corresponds to Philippine time.

(2) Yes, I received the email.

--

Having said these, please verify 
in the log file,  the email that Auto-email 
was unable to automatically send.

I set its "Target Kick Time" to: 
`2018-05-27 07:56:21`

It threw the following error based on the log file:

> ERROR - 2018-05-27 07:55:00 --> 404 Page Not Found: Robotstxt/index

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

On Mon, May 28, 2018, 8:49 AM Masarap Mabuhay, <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the replies.
>
> (1) Yes, for the email I sent on 2018-05-27 07:53, I used the "Send
> Email" button.
> --> 07:53 already corresponds to Philippine time.
>
Ok.

> (2) Yes, I received the email.
>
> --
>
> Having said these, please verify
> in the log file, the email that Auto-email
> was unable to automatically send.
>
> I set its "Target Kick Time" to:
> 2018-05-27 07:56:21
>
> It threw the following error based on the log file:
>
> ERROR - 2018-05-27 07:55:00 --> 404 Page Not Found: Robotstxt/index
>
> The error message above is not related to auto email.

Request:

(1) pls send me instruction on how to access ur live server using ssh.

(2) pls send me the ff also:
      (A) the exact command u used

      (B) in what directory you executed the command

(3) pls send me exact steps you did to configure your cron.

Morning!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the reply.

**(1) Here is the link to the instructions on how to access prod/live server using ssh from a Linux machine:**
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html; 
last accessed: 20180529
--> You will need the private key.
--> Please tell me if (1) accessing the live server is really necessary.

**(2) This is the command I used to run the `cron` script.**
(A) `php index.php auto-email/autoemail run`
--> Reference: https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature; last accessed: 20180529
(B) I executed the command in the directory where the application, assets, etc folders are located on prod.

**(3) As for the steps to configure `cron`, I used the following:**
(A) https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature
(B) https://github.com/usbong/UsbongStore/tree/master/auto-email
--> `usbong_store_auto_email_v08.sql`

Please never hesitate
to ask me if there's anything
you'd want me to clarify.

Thank you.

Peace,
Mike

**Comment by zent-lim** [comment]
Hi Mike,

Any of the ff is ok with me, below are downsides of each:
(1) I visit you - let s schedule next week?
(2) direct access through ssh - I might damage some files accidentally
(3) continue through email - long turn around time

Shall we meet instead?

If yes, does June 6 0900 am work for you?
If no, I'll work on generating a key for ssh.

Thanks!

**Comment by zent-lim** [comment]
Or how about this evening?

I have a 3 pm at Katipunan. Maybe I can go to Usbong after.

Morning!

**Comment by zent-lim** [comment]
Hi Mike,

On Tue, May 29, 2018, 9:21 AM Masarap Mabuhay, <notifications@github.com>
wrote:

> Hi Zent,
> Thank you for the reply.
>
> *(1) Here is the link to the instructions on how to access prod/live
> server using ssh from a Linux machine:*
>
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html
> ;
> last accessed: 20180529
> --> You will need the private key.
> --> Please tell me if (1) accessing the live server is really necessary.
>
> *(2) This is the command I used to run the cron script.*
> (A) php index.php auto-email/autoemail run
> --> Reference:
> https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature; last
> accessed: 20180529
>
This looks correct.

> (B) I executed the command in the directory where the application, assets,
> etc folders are located on prod.
>
This looks correct.

Let s figure it out thuraday 9 am then.

See you!

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for your 
replies here on GitHub,
which also forward them 
to me via email.

As we agreed over SMS/txt messaging, 
I'll prepare the Usbong HQ office
for our meeting this Thursday 
(May 31, 2018), at 9am - 11am.

Please never hesitate
to tell me if there's
anything that you need
for our meeting.

Thank you.

Peace,
Mike

**Comment by masarapmabuhay** [comment]
Hi Zent,
I am now closing this issue,
since we've already resolved it.

Thank you for visiting me 
at the Usbong HQ as well.

Having said this, I've updated
the Auto-email Wiki accordingly:
https://github.com/usbong/UsbongStore/wiki/Auto-Email-Feature

Peace,
Mike

**Comment by zent-lim** [comment]
U re welcome! I enjoyed the tea. 😁😁😁

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the response.

OK!

Here's something that I wrote about it:
https://store.usbong.ph/w/MandS-Earl-Grey-Tea-/28

I'll replenish the supply
of our Green Tea product,
so I can offer it to you
when you come and visit.

Having said this, please 
never hesitate to tell me 
if you want to order 
teas from our store!

Thank you!

Peace,
Mike

**Comment by zent-lim** [comment]
Okly dokly!

P.s.
Can t open the url in mobile. Usbong store redirected me to app. Then app
showed books instead of tea. 🙂

**Comment by masarapmabuhay** [comment]
OK, Zent! Thank you!

Peace,
Mike
p.s. Can you open a new issue here on GitHub for the problem you experienced? If you can provide the steps so I can replicate it, that would be even better. I'm guessing you'll have to do a finger slide from right to left on the categories row for the app to show the Tea category/product type.

**Comment by zent-lim** [comment]
Morning Mike!

A bit busy today. Catch up w u soon. 😊

**Comment by zent-lim** [comment]
P.s.
There is noise circling around that MS is buying github. Better back up ur
files just in case there are changes in terms of agreement. I tagged u at
FB. ☺

**Comment by masarapmabuhay** [comment]
Hi Zent,
Thank you for the replies!

OK!

Peace,
Mike
p.s. OK! Thank you for the advice.
